// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	backend "github.com/mikhailbolshakov/ocpi/backend"

	domain "github.com/mikhailbolshakov/ocpi/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Adapter is an autogenerated mock type for the Adapter type
type Adapter struct {
	mock.Mock
}

// Close provides a mock function with given fields: ctx
func (_m *Adapter) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateChargingPeriods provides a mock function with given fields: ctx, sess, periods
func (_m *Adapter) CreateChargingPeriods(ctx context.Context, sess *domain.Session, periods []*domain.ChargingPeriod) error {
	ret := _m.Called(ctx, sess, periods)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session, []*domain.ChargingPeriod) error); ok {
		r0 = rf(ctx, sess, periods)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCommand provides a mock function with given fields: ctx, cmd
func (_m *Adapter) CreateCommand(ctx context.Context, cmd *domain.Command) error {
	ret := _m.Called(ctx, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateParty provides a mock function with given fields: ctx, party
func (_m *Adapter) CreateParty(ctx context.Context, party *domain.Party) error {
	ret := _m.Called(ctx, party)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Party) error); ok {
		r0 = rf(ctx, party)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePlatform provides a mock function with given fields: ctx, p
func (_m *Adapter) CreatePlatform(ctx context.Context, p *domain.Platform) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Platform) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWebhook provides a mock function with given fields: ctx, wh
func (_m *Adapter) CreateWebhook(ctx context.Context, wh *backend.Webhook) error {
	ret := _m.Called(ctx, wh)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) error); ok {
		r0 = rf(ctx, wh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCdrsByExtId provides a mock function with given fields: ctx, extId
func (_m *Adapter) DeleteCdrsByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCommand provides a mock function with given fields: ctx, cmdId
func (_m *Adapter) DeleteCommand(ctx context.Context, cmdId string) error {
	ret := _m.Called(ctx, cmdId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, cmdId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCommandsByExt provides a mock function with given fields: ctx, extId
func (_m *Adapter) DeleteCommandsByExt(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLocationsByExtId provides a mock function with given fields: ctx, extId
func (_m *Adapter) DeleteLocationsByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePartyByExtId provides a mock function with given fields: ctx, extId
func (_m *Adapter) DeletePartyByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePlatform provides a mock function with given fields: ctx, p
func (_m *Adapter) DeletePlatform(ctx context.Context, p *domain.Platform) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Platform) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSessionsByExtId provides a mock function with given fields: ctx, extId
func (_m *Adapter) DeleteSessionsByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTariffsByExtId provides a mock function with given fields: ctx, extId
func (_m *Adapter) DeleteTariffsByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTokensByExtId provides a mock function with given fields: ctx, extId
func (_m *Adapter) DeleteTokensByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWebhook provides a mock function with given fields: ctx, whId
func (_m *Adapter) DeleteWebhook(ctx context.Context, whId string) error {
	ret := _m.Called(ctx, whId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, whId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByRefId provides a mock function with given fields: ctx, refId
func (_m *Adapter) GetByRefId(ctx context.Context, refId string) (*domain.Party, error) {
	ret := _m.Called(ctx, refId)

	var r0 *domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Party, error)); ok {
		return rf(ctx, refId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Party); ok {
		r0 = rf(ctx, refId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCdr provides a mock function with given fields: ctx, sessId
func (_m *Adapter) GetCdr(ctx context.Context, sessId string) (*domain.Cdr, error) {
	ret := _m.Called(ctx, sessId)

	var r0 *domain.Cdr
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Cdr, error)); ok {
		return rf(ctx, sessId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Cdr); ok {
		r0 = rf(ctx, sessId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cdr)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChargingPeriods provides a mock function with given fields: ctx, sessIds
func (_m *Adapter) GetChargingPeriods(ctx context.Context, sessIds ...string) (map[string][]*domain.ChargingPeriod, error) {
	_va := make([]interface{}, len(sessIds))
	for _i := range sessIds {
		_va[_i] = sessIds[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 map[string][]*domain.ChargingPeriod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) (map[string][]*domain.ChargingPeriod, error)); ok {
		return rf(ctx, sessIds...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...string) map[string][]*domain.ChargingPeriod); ok {
		r0 = rf(ctx, sessIds...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]*domain.ChargingPeriod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = rf(ctx, sessIds...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommand provides a mock function with given fields: ctx, cmdId
func (_m *Adapter) GetCommand(ctx context.Context, cmdId string) (*domain.Command, error) {
	ret := _m.Called(ctx, cmdId)

	var r0 *domain.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Command, error)); ok {
		return rf(ctx, cmdId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Command); ok {
		r0 = rf(ctx, cmdId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cmdId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommandByAuthRef provides a mock function with given fields: ctx, authRef
func (_m *Adapter) GetCommandByAuthRef(ctx context.Context, authRef string) (*domain.Command, error) {
	ret := _m.Called(ctx, authRef)

	var r0 *domain.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Command, error)); ok {
		return rf(ctx, authRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Command); ok {
		r0 = rf(ctx, authRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, authRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConnector provides a mock function with given fields: ctx, locId, evseId, conId
func (_m *Adapter) GetConnector(ctx context.Context, locId string, evseId string, conId string) (*domain.Connector, error) {
	ret := _m.Called(ctx, locId, evseId, conId)

	var r0 *domain.Connector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.Connector, error)); ok {
		return rf(ctx, locId, evseId, conId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.Connector); ok {
		r0 = rf(ctx, locId, evseId, conId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, locId, evseId, conId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEvse provides a mock function with given fields: ctx, locId, evseId, withConnectors
func (_m *Adapter) GetEvse(ctx context.Context, locId string, evseId string, withConnectors bool) (*domain.Evse, error) {
	ret := _m.Called(ctx, locId, evseId, withConnectors)

	var r0 *domain.Evse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*domain.Evse, error)); ok {
		return rf(ctx, locId, evseId, withConnectors)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *domain.Evse); ok {
		r0 = rf(ctx, locId, evseId, withConnectors)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Evse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, locId, evseId, withConnectors)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocation provides a mock function with given fields: ctx, id, withEvse
func (_m *Adapter) GetLocation(ctx context.Context, id string, withEvse bool) (*domain.Location, error) {
	ret := _m.Called(ctx, id, withEvse)

	var r0 *domain.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*domain.Location, error)); ok {
		return rf(ctx, id, withEvse)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *domain.Location); ok {
		r0 = rf(ctx, id, withEvse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, id, withEvse)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartiesByPlatform provides a mock function with given fields: ctx, platformId
func (_m *Adapter) GetPartiesByPlatform(ctx context.Context, platformId string) ([]*domain.Party, error) {
	ret := _m.Called(ctx, platformId)

	var r0 []*domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Party, error)); ok {
		return rf(ctx, platformId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Party); ok {
		r0 = rf(ctx, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, platformId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParty provides a mock function with given fields: ctx, id
func (_m *Adapter) GetParty(ctx context.Context, id string) (*domain.Party, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Party, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Party); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartyByExtId provides a mock function with given fields: ctx, extId
func (_m *Adapter) GetPartyByExtId(ctx context.Context, extId domain.PartyExtId) (*domain.Party, error) {
	ret := _m.Called(ctx, extId)

	var r0 *domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) (*domain.Party, error)); ok {
		return rf(ctx, extId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) *domain.Party); ok {
		r0 = rf(ctx, extId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PartyExtId) error); ok {
		r1 = rf(ctx, extId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlatform provides a mock function with given fields: ctx, id
func (_m *Adapter) GetPlatform(ctx context.Context, id string) (*domain.Platform, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Platform, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Platform); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlatformByTokenA provides a mock function with given fields: ctx, tokenA
func (_m *Adapter) GetPlatformByTokenA(ctx context.Context, tokenA domain.PlatformToken) (*domain.Platform, error) {
	ret := _m.Called(ctx, tokenA)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) (*domain.Platform, error)); ok {
		return rf(ctx, tokenA)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) *domain.Platform); ok {
		r0 = rf(ctx, tokenA)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PlatformToken) error); ok {
		r1 = rf(ctx, tokenA)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlatformByTokenB provides a mock function with given fields: ctx, token
func (_m *Adapter) GetPlatformByTokenB(ctx context.Context, token domain.PlatformToken) (*domain.Platform, error) {
	ret := _m.Called(ctx, token)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) (*domain.Platform, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) *domain.Platform); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PlatformToken) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlatformByTokenC provides a mock function with given fields: ctx, token
func (_m *Adapter) GetPlatformByTokenC(ctx context.Context, token domain.PlatformToken) (*domain.Platform, error) {
	ret := _m.Called(ctx, token)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) (*domain.Platform, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) *domain.Platform); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PlatformToken) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSession provides a mock function with given fields: ctx, sessId, withChargingPeriods
func (_m *Adapter) GetSession(ctx context.Context, sessId string, withChargingPeriods bool) (*domain.Session, error) {
	ret := _m.Called(ctx, sessId, withChargingPeriods)

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*domain.Session, error)); ok {
		return rf(ctx, sessId, withChargingPeriods)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *domain.Session); ok {
		r0 = rf(ctx, sessId, withChargingPeriods)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, sessId, withChargingPeriods)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTariff provides a mock function with given fields: ctx, trfId
func (_m *Adapter) GetTariff(ctx context.Context, trfId string) (*domain.Tariff, error) {
	ret := _m.Called(ctx, trfId)

	var r0 *domain.Tariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Tariff, error)); ok {
		return rf(ctx, trfId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Tariff); ok {
		r0 = rf(ctx, trfId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trfId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetToken provides a mock function with given fields: ctx, tknId
func (_m *Adapter) GetToken(ctx context.Context, tknId string) (*domain.Token, error) {
	ret := _m.Called(ctx, tknId)

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Token, error)); ok {
		return rf(ctx, tknId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Token); ok {
		r0 = rf(ctx, tknId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tknId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWebhook provides a mock function with given fields: ctx, whId
func (_m *Adapter) GetWebhook(ctx context.Context, whId string) (*backend.Webhook, error) {
	ret := _m.Called(ctx, whId)

	var r0 *backend.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*backend.Webhook, error)); ok {
		return rf(ctx, whId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *backend.Webhook); ok {
		r0 = rf(ctx, whId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, whId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields: ctx, cfg
func (_m *Adapter) Init(ctx context.Context, cfg interface{}) error {
	ret := _m.Called(ctx, cfg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkSentParties provides a mock function with given fields: ctx, date, partyIds
func (_m *Adapter) MarkSentParties(ctx context.Context, date time.Time, partyIds ...string) error {
	_va := make([]interface{}, len(partyIds))
	for _i := range partyIds {
		_va[_i] = partyIds[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, date)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, ...string) error); ok {
		r0 = rf(ctx, date, partyIds...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MergeCdr provides a mock function with given fields: ctx, sess
func (_m *Adapter) MergeCdr(ctx context.Context, sess *domain.Cdr) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Cdr) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MergeConnector provides a mock function with given fields: ctx, con
func (_m *Adapter) MergeConnector(ctx context.Context, con *domain.Connector) error {
	ret := _m.Called(ctx, con)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Connector) error); ok {
		r0 = rf(ctx, con)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MergeEvse provides a mock function with given fields: ctx, evse
func (_m *Adapter) MergeEvse(ctx context.Context, evse *domain.Evse) error {
	ret := _m.Called(ctx, evse)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Evse) error); ok {
		r0 = rf(ctx, evse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MergeLocation provides a mock function with given fields: ctx, loc
func (_m *Adapter) MergeLocation(ctx context.Context, loc *domain.Location) error {
	ret := _m.Called(ctx, loc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Location) error); ok {
		r0 = rf(ctx, loc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MergeSession provides a mock function with given fields: ctx, sess
func (_m *Adapter) MergeSession(ctx context.Context, sess *domain.Session) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MergeTariff provides a mock function with given fields: ctx, trf
func (_m *Adapter) MergeTariff(ctx context.Context, trf *domain.Tariff) error {
	ret := _m.Called(ctx, trf)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tariff) error); ok {
		r0 = rf(ctx, trf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MergeToken provides a mock function with given fields: ctx, tkn
func (_m *Adapter) MergeToken(ctx context.Context, tkn *domain.Token) error {
	ret := _m.Called(ctx, tkn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = rf(ctx, tkn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MergeWebhook provides a mock function with given fields: ctx, wh
func (_m *Adapter) MergeWebhook(ctx context.Context, wh *backend.Webhook) error {
	ret := _m.Called(ctx, wh)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) error); ok {
		r0 = rf(ctx, wh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, msg
func (_m *Adapter) Save(ctx context.Context, msg *domain.LogMessage) {
	_m.Called(ctx, msg)
}

// Search provides a mock function with given fields: ctx, criteria
func (_m *Adapter) Search(ctx context.Context, criteria *domain.PartySearchCriteria) (*domain.PartySearchResponse, error) {
	ret := _m.Called(ctx, criteria)

	var r0 *domain.PartySearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PartySearchCriteria) (*domain.PartySearchResponse, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PartySearchCriteria) *domain.PartySearchResponse); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PartySearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.PartySearchCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCdrs provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchCdrs(ctx context.Context, cr *domain.CdrSearchCriteria) (*domain.CdrSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.CdrSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CdrSearchCriteria) (*domain.CdrSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CdrSearchCriteria) *domain.CdrSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CdrSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CdrSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCommands provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchCommands(ctx context.Context, cr *domain.CommandSearchCriteria) (*domain.CommandSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.CommandSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommandSearchCriteria) (*domain.CommandSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommandSearchCriteria) *domain.CommandSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommandSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CommandSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchConnectors provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchConnectors(ctx context.Context, cr *domain.ConnectorSearchCriteria) (*domain.ConnectorSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.ConnectorSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ConnectorSearchCriteria) (*domain.ConnectorSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ConnectorSearchCriteria) *domain.ConnectorSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ConnectorSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.ConnectorSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchEvses provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchEvses(ctx context.Context, cr *domain.EvseSearchCriteria) (*domain.EvseSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.EvseSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EvseSearchCriteria) (*domain.EvseSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.EvseSearchCriteria) *domain.EvseSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EvseSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.EvseSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchLocations provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchLocations(ctx context.Context, cr *domain.LocationSearchCriteria) (*domain.LocationSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.LocationSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.LocationSearchCriteria) (*domain.LocationSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.LocationSearchCriteria) *domain.LocationSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LocationSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.LocationSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchLog provides a mock function with given fields: ctx, criteria
func (_m *Adapter) SearchLog(ctx context.Context, criteria *domain.SearchLogCriteria) ([]*domain.LogMessage, error) {
	ret := _m.Called(ctx, criteria)

	var r0 []*domain.LogMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SearchLogCriteria) ([]*domain.LogMessage, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SearchLogCriteria) []*domain.LogMessage); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.LogMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.SearchLogCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchPlatforms provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchPlatforms(ctx context.Context, cr *domain.PlatformSearchCriteria) ([]*domain.Platform, error) {
	ret := _m.Called(ctx, cr)

	var r0 []*domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PlatformSearchCriteria) ([]*domain.Platform, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PlatformSearchCriteria) []*domain.Platform); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.PlatformSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchSessions provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchSessions(ctx context.Context, cr *domain.SessionSearchCriteria) (*domain.SessionSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.SessionSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SessionSearchCriteria) (*domain.SessionSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SessionSearchCriteria) *domain.SessionSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SessionSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.SessionSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchTariffs provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchTariffs(ctx context.Context, cr *domain.TariffSearchCriteria) (*domain.TariffSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.TariffSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TariffSearchCriteria) (*domain.TariffSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TariffSearchCriteria) *domain.TariffSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TariffSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TariffSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchTokens provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchTokens(ctx context.Context, cr *domain.TokenSearchCriteria) (*domain.TokenSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.TokenSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TokenSearchCriteria) (*domain.TokenSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TokenSearchCriteria) *domain.TokenSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TokenSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchWebhook provides a mock function with given fields: ctx, cr
func (_m *Adapter) SearchWebhook(ctx context.Context, cr *backend.SearchWebhookCriteria) ([]*backend.Webhook, error) {
	ret := _m.Called(ctx, cr)

	var r0 []*backend.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.SearchWebhookCriteria) ([]*backend.Webhook, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.SearchWebhookCriteria) []*backend.Webhook); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.SearchWebhookCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCdr provides a mock function with given fields: ctx, sess
func (_m *Adapter) UpdateCdr(ctx context.Context, sess *domain.Cdr) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Cdr) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateChargingPeriods provides a mock function with given fields: ctx, sess, periods
func (_m *Adapter) UpdateChargingPeriods(ctx context.Context, sess *domain.Session, periods []*domain.ChargingPeriod) error {
	ret := _m.Called(ctx, sess, periods)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session, []*domain.ChargingPeriod) error); ok {
		r0 = rf(ctx, sess, periods)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCommand provides a mock function with given fields: ctx, cmd
func (_m *Adapter) UpdateCommand(ctx context.Context, cmd *domain.Command) error {
	ret := _m.Called(ctx, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateConnector provides a mock function with given fields: ctx, con
func (_m *Adapter) UpdateConnector(ctx context.Context, con *domain.Connector) error {
	ret := _m.Called(ctx, con)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Connector) error); ok {
		r0 = rf(ctx, con)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEvse provides a mock function with given fields: ctx, evse
func (_m *Adapter) UpdateEvse(ctx context.Context, evse *domain.Evse) error {
	ret := _m.Called(ctx, evse)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Evse) error); ok {
		r0 = rf(ctx, evse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLocation provides a mock function with given fields: ctx, loc
func (_m *Adapter) UpdateLocation(ctx context.Context, loc *domain.Location) error {
	ret := _m.Called(ctx, loc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Location) error); ok {
		r0 = rf(ctx, loc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateParty provides a mock function with given fields: ctx, party
func (_m *Adapter) UpdateParty(ctx context.Context, party *domain.Party) error {
	ret := _m.Called(ctx, party)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Party) error); ok {
		r0 = rf(ctx, party)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePlatform provides a mock function with given fields: ctx, p
func (_m *Adapter) UpdatePlatform(ctx context.Context, p *domain.Platform) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Platform) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSession provides a mock function with given fields: ctx, sess
func (_m *Adapter) UpdateSession(ctx context.Context, sess *domain.Session) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTariff provides a mock function with given fields: ctx, trf
func (_m *Adapter) UpdateTariff(ctx context.Context, trf *domain.Tariff) error {
	ret := _m.Called(ctx, trf)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tariff) error); ok {
		r0 = rf(ctx, trf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateToken provides a mock function with given fields: ctx, tkn
func (_m *Adapter) UpdateToken(ctx context.Context, tkn *domain.Token) error {
	ret := _m.Called(ctx, tkn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = rf(ctx, tkn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWebhook provides a mock function with given fields: ctx, wh
func (_m *Adapter) UpdateWebhook(ctx context.Context, wh *backend.Webhook) error {
	ret := _m.Called(ctx, wh)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) error); ok {
		r0 = rf(ctx, wh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAdapter creates a new instance of Adapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Adapter {
	mock := &Adapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
