// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	backend "github.com/mikhailbolshakov/ocpi/backend"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mikhailbolshakov/ocpi/model"
)

// CdrConverter is an autogenerated mock type for the CdrConverter type
type CdrConverter struct {
	mock.Mock
}

// CdrBackendToDomain provides a mock function with given fields: cdr, sess, loc, evse, con
func (_m *CdrConverter) CdrBackendToDomain(cdr *backend.Cdr, sess *domain.Session, loc *domain.Location, evse *domain.Evse, con *domain.Connector) *domain.Cdr {
	ret := _m.Called(cdr, sess, loc, evse, con)

	var r0 *domain.Cdr
	if rf, ok := ret.Get(0).(func(*backend.Cdr, *domain.Session, *domain.Location, *domain.Evse, *domain.Connector) *domain.Cdr); ok {
		r0 = rf(cdr, sess, loc, evse, con)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cdr)
		}
	}

	return r0
}

// CdrDomainToBackend provides a mock function with given fields: cdr
func (_m *CdrConverter) CdrDomainToBackend(cdr *domain.Cdr) *backend.Cdr {
	ret := _m.Called(cdr)

	var r0 *backend.Cdr
	if rf, ok := ret.Get(0).(func(*domain.Cdr) *backend.Cdr); ok {
		r0 = rf(cdr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Cdr)
		}
	}

	return r0
}

// CdrDomainToModel provides a mock function with given fields: cdr
func (_m *CdrConverter) CdrDomainToModel(cdr *domain.Cdr) *model.OcpiCdr {
	ret := _m.Called(cdr)

	var r0 *model.OcpiCdr
	if rf, ok := ret.Get(0).(func(*domain.Cdr) *model.OcpiCdr); ok {
		r0 = rf(cdr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCdr)
		}
	}

	return r0
}

// CdrModelToDomain provides a mock function with given fields: cdr, platformId
func (_m *CdrConverter) CdrModelToDomain(cdr *model.OcpiCdr, platformId string) *domain.Cdr {
	ret := _m.Called(cdr, platformId)

	var r0 *domain.Cdr
	if rf, ok := ret.Get(0).(func(*model.OcpiCdr, string) *domain.Cdr); ok {
		r0 = rf(cdr, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cdr)
		}
	}

	return r0
}

// CdrsDomainToBackend provides a mock function with given fields: ts
func (_m *CdrConverter) CdrsDomainToBackend(ts []*domain.Cdr) []*backend.Cdr {
	ret := _m.Called(ts)

	var r0 []*backend.Cdr
	if rf, ok := ret.Get(0).(func([]*domain.Cdr) []*backend.Cdr); ok {
		r0 = rf(ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Cdr)
		}
	}

	return r0
}

// CdrsDomainToModel provides a mock function with given fields: ts
func (_m *CdrConverter) CdrsDomainToModel(ts []*domain.Cdr) []*model.OcpiCdr {
	ret := _m.Called(ts)

	var r0 []*model.OcpiCdr
	if rf, ok := ret.Get(0).(func([]*domain.Cdr) []*model.OcpiCdr); ok {
		r0 = rf(ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiCdr)
		}
	}

	return r0
}

// NewCdrConverter creates a new instance of CdrConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCdrConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CdrConverter {
	mock := &CdrConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
