// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// CdrStorage is an autogenerated mock type for the CdrStorage type
type CdrStorage struct {
	mock.Mock
}

// DeleteCdrsByExtId provides a mock function with given fields: ctx, extId
func (_m *CdrStorage) DeleteCdrsByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCdr provides a mock function with given fields: ctx, sessId
func (_m *CdrStorage) GetCdr(ctx context.Context, sessId string) (*domain.Cdr, error) {
	ret := _m.Called(ctx, sessId)

	var r0 *domain.Cdr
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Cdr, error)); ok {
		return rf(ctx, sessId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Cdr); ok {
		r0 = rf(ctx, sessId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cdr)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergeCdr provides a mock function with given fields: ctx, sess
func (_m *CdrStorage) MergeCdr(ctx context.Context, sess *domain.Cdr) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Cdr) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchCdrs provides a mock function with given fields: ctx, cr
func (_m *CdrStorage) SearchCdrs(ctx context.Context, cr *domain.CdrSearchCriteria) (*domain.CdrSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.CdrSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CdrSearchCriteria) (*domain.CdrSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CdrSearchCriteria) *domain.CdrSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CdrSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CdrSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCdr provides a mock function with given fields: ctx, sess
func (_m *CdrStorage) UpdateCdr(ctx context.Context, sess *domain.Cdr) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Cdr) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCdrStorage creates a new instance of CdrStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCdrStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *CdrStorage {
	mock := &CdrStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
