// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	backend "github.com/mikhailbolshakov/ocpi/backend"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mikhailbolshakov/ocpi/model"

	time "time"
)

// CdrUc is an autogenerated mock type for the CdrUc type
type CdrUc struct {
	mock.Mock
}

// OnLocalCdrChanged provides a mock function with given fields: ctx, cdr
func (_m *CdrUc) OnLocalCdrChanged(ctx context.Context, cdr *backend.Cdr) error {
	ret := _m.Called(ctx, cdr)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Cdr) error); ok {
		r0 = rf(ctx, cdr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteCdrPut provides a mock function with given fields: ctx, platformId, cdr
func (_m *CdrUc) OnRemoteCdrPut(ctx context.Context, platformId string, cdr *model.OcpiCdr) error {
	ret := _m.Called(ctx, platformId, cdr)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiCdr) error); ok {
		r0 = rf(ctx, platformId, cdr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteCdrsPull provides a mock function with given fields: ctx, from, to
func (_m *CdrUc) OnRemoteCdrsPull(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteCdrsPullWhenPushNotSupported provides a mock function with given fields: ctx, from, to
func (_m *CdrUc) OnRemoteCdrsPullWhenPushNotSupported(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCdrUc creates a new instance of CdrUc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCdrUc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CdrUc {
	mock := &CdrUc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
