// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// CommandStorage is an autogenerated mock type for the CommandStorage type
type CommandStorage struct {
	mock.Mock
}

// CreateCommand provides a mock function with given fields: ctx, cmd
func (_m *CommandStorage) CreateCommand(ctx context.Context, cmd *domain.Command) error {
	ret := _m.Called(ctx, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCommand provides a mock function with given fields: ctx, cmdId
func (_m *CommandStorage) DeleteCommand(ctx context.Context, cmdId string) error {
	ret := _m.Called(ctx, cmdId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, cmdId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCommandsByExt provides a mock function with given fields: ctx, extId
func (_m *CommandStorage) DeleteCommandsByExt(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCommand provides a mock function with given fields: ctx, cmdId
func (_m *CommandStorage) GetCommand(ctx context.Context, cmdId string) (*domain.Command, error) {
	ret := _m.Called(ctx, cmdId)

	var r0 *domain.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Command, error)); ok {
		return rf(ctx, cmdId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Command); ok {
		r0 = rf(ctx, cmdId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cmdId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommandByAuthRef provides a mock function with given fields: ctx, authRef
func (_m *CommandStorage) GetCommandByAuthRef(ctx context.Context, authRef string) (*domain.Command, error) {
	ret := _m.Called(ctx, authRef)

	var r0 *domain.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Command, error)); ok {
		return rf(ctx, authRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Command); ok {
		r0 = rf(ctx, authRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, authRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCommands provides a mock function with given fields: ctx, cr
func (_m *CommandStorage) SearchCommands(ctx context.Context, cr *domain.CommandSearchCriteria) (*domain.CommandSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.CommandSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommandSearchCriteria) (*domain.CommandSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommandSearchCriteria) *domain.CommandSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommandSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CommandSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCommand provides a mock function with given fields: ctx, cmd
func (_m *CommandStorage) UpdateCommand(ctx context.Context, cmd *domain.Command) error {
	ret := _m.Called(ctx, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommandStorage creates a new instance of CommandStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandStorage {
	mock := &CommandStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
