// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	backend "github.com/mikhailbolshakov/ocpi/backend"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mikhailbolshakov/ocpi/model"
)

// CommandConverter is an autogenerated mock type for the CommandConverter type
type CommandConverter struct {
	mock.Mock
}

// CancelReservationCommandBackendToDomain provides a mock function with given fields: cmd, platformId
func (_m *CommandConverter) CancelReservationCommandBackendToDomain(cmd *backend.CancelReservationRequest, platformId string) *domain.Command {
	ret := _m.Called(cmd, platformId)

	var r0 *domain.Command
	if rf, ok := ret.Get(0).(func(*backend.CancelReservationRequest, string) *domain.Command); ok {
		r0 = rf(cmd, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	return r0
}

// CancelReservationCommandDomainToModel provides a mock function with given fields: cmd
func (_m *CommandConverter) CancelReservationCommandDomainToModel(cmd *domain.Command) *model.OcpiCancelReservation {
	ret := _m.Called(cmd)

	var r0 *model.OcpiCancelReservation
	if rf, ok := ret.Get(0).(func(*domain.Command) *model.OcpiCancelReservation); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCancelReservation)
		}
	}

	return r0
}

// CancelReservationCommandModelToDomain provides a mock function with given fields: cmd, platformId
func (_m *CommandConverter) CancelReservationCommandModelToDomain(cmd *model.OcpiCancelReservation, platformId string) *domain.Command {
	ret := _m.Called(cmd, platformId)

	var r0 *domain.Command
	if rf, ok := ret.Get(0).(func(*model.OcpiCancelReservation, string) *domain.Command); ok {
		r0 = rf(cmd, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	return r0
}

// CommandDomainToBackend provides a mock function with given fields: cmd
func (_m *CommandConverter) CommandDomainToBackend(cmd *domain.Command) *backend.Command {
	ret := _m.Called(cmd)

	var r0 *backend.Command
	if rf, ok := ret.Get(0).(func(*domain.Command) *backend.Command); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Command)
		}
	}

	return r0
}

// CommandsDomainToBackend provides a mock function with given fields: commands
func (_m *CommandConverter) CommandsDomainToBackend(commands []*domain.Command) []*backend.Command {
	ret := _m.Called(commands)

	var r0 []*backend.Command
	if rf, ok := ret.Get(0).(func([]*domain.Command) []*backend.Command); ok {
		r0 = rf(commands)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Command)
		}
	}

	return r0
}

// ReserveNowCommandBackendToDomain provides a mock function with given fields: cmd, platformId
func (_m *CommandConverter) ReserveNowCommandBackendToDomain(cmd *backend.ReserveNowRequest, platformId string) *domain.Command {
	ret := _m.Called(cmd, platformId)

	var r0 *domain.Command
	if rf, ok := ret.Get(0).(func(*backend.ReserveNowRequest, string) *domain.Command); ok {
		r0 = rf(cmd, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	return r0
}

// ReserveNowCommandDomainToModel provides a mock function with given fields: cmd
func (_m *CommandConverter) ReserveNowCommandDomainToModel(cmd *domain.Command) *model.OcpiReserveNow {
	ret := _m.Called(cmd)

	var r0 *model.OcpiReserveNow
	if rf, ok := ret.Get(0).(func(*domain.Command) *model.OcpiReserveNow); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiReserveNow)
		}
	}

	return r0
}

// ReserveNowCommandModelToDomain provides a mock function with given fields: cmd, platformId
func (_m *CommandConverter) ReserveNowCommandModelToDomain(cmd *model.OcpiReserveNow, platformId string) *domain.Command {
	ret := _m.Called(cmd, platformId)

	var r0 *domain.Command
	if rf, ok := ret.Get(0).(func(*model.OcpiReserveNow, string) *domain.Command); ok {
		r0 = rf(cmd, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	return r0
}

// StartSessionCommandBackendToDomain provides a mock function with given fields: cmd, platformId
func (_m *CommandConverter) StartSessionCommandBackendToDomain(cmd *backend.StartSessionRequest, platformId string) *domain.Command {
	ret := _m.Called(cmd, platformId)

	var r0 *domain.Command
	if rf, ok := ret.Get(0).(func(*backend.StartSessionRequest, string) *domain.Command); ok {
		r0 = rf(cmd, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	return r0
}

// StartSessionCommandDomainToModel provides a mock function with given fields: cmd
func (_m *CommandConverter) StartSessionCommandDomainToModel(cmd *domain.Command) *model.OcpiStartSession {
	ret := _m.Called(cmd)

	var r0 *model.OcpiStartSession
	if rf, ok := ret.Get(0).(func(*domain.Command) *model.OcpiStartSession); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiStartSession)
		}
	}

	return r0
}

// StartSessionCommandModelToDomain provides a mock function with given fields: cmd, platformId
func (_m *CommandConverter) StartSessionCommandModelToDomain(cmd *model.OcpiStartSession, platformId string) *domain.Command {
	ret := _m.Called(cmd, platformId)

	var r0 *domain.Command
	if rf, ok := ret.Get(0).(func(*model.OcpiStartSession, string) *domain.Command); ok {
		r0 = rf(cmd, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	return r0
}

// StopSessionCommandBackendToDomain provides a mock function with given fields: cmd, platformId
func (_m *CommandConverter) StopSessionCommandBackendToDomain(cmd *backend.StopSessionRequest, platformId string) *domain.Command {
	ret := _m.Called(cmd, platformId)

	var r0 *domain.Command
	if rf, ok := ret.Get(0).(func(*backend.StopSessionRequest, string) *domain.Command); ok {
		r0 = rf(cmd, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	return r0
}

// StopSessionCommandDomainToModel provides a mock function with given fields: cmd
func (_m *CommandConverter) StopSessionCommandDomainToModel(cmd *domain.Command) *model.OcpiStopSession {
	ret := _m.Called(cmd)

	var r0 *model.OcpiStopSession
	if rf, ok := ret.Get(0).(func(*domain.Command) *model.OcpiStopSession); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiStopSession)
		}
	}

	return r0
}

// StopSessionCommandModelToDomain provides a mock function with given fields: cmd, platformId
func (_m *CommandConverter) StopSessionCommandModelToDomain(cmd *model.OcpiStopSession, platformId string) *domain.Command {
	ret := _m.Called(cmd, platformId)

	var r0 *domain.Command
	if rf, ok := ret.Get(0).(func(*model.OcpiStopSession, string) *domain.Command); ok {
		r0 = rf(cmd, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	return r0
}

// NewCommandConverter creates a new instance of CommandConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandConverter {
	mock := &CommandConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
