// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// CommandService is an autogenerated mock type for the CommandService type
type CommandService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, cmd
func (_m *CommandService) Create(ctx context.Context, cmd *domain.Command) (*domain.Command, error) {
	ret := _m.Called(ctx, cmd)

	var r0 *domain.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) (*domain.Command, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) *domain.Command); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Command) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCommandsByExt provides a mock function with given fields: ctx, extId
func (_m *CommandService) DeleteCommandsByExt(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *CommandService) Get(ctx context.Context, id string) (*domain.Command, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Command, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Command); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAuthRef provides a mock function with given fields: ctx, authRef
func (_m *CommandService) GetByAuthRef(ctx context.Context, authRef string) (*domain.Command, error) {
	ret := _m.Called(ctx, authRef)

	var r0 *domain.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Command, error)); ok {
		return rf(ctx, authRef)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Command); ok {
		r0 = rf(ctx, authRef)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, authRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCommands provides a mock function with given fields: ctx, cr
func (_m *CommandService) SearchCommands(ctx context.Context, cr *domain.CommandSearchCriteria) (*domain.CommandSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.CommandSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommandSearchCriteria) (*domain.CommandSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommandSearchCriteria) *domain.CommandSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommandSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CommandSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, cmd
func (_m *CommandService) Update(ctx context.Context, cmd *domain.Command) (*domain.Command, error) {
	ret := _m.Called(ctx, cmd)

	var r0 *domain.Command
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) (*domain.Command, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) *domain.Command); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Command)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Command) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommandService creates a new instance of CommandService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandService {
	mock := &CommandService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
