// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	model "github.com/mikhailbolshakov/ocpi/model"
)

// CommandUc is an autogenerated mock type for the CommandUc type
type CommandUc struct {
	mock.Mock
}

// LocalCommandsDeadlineCronHandler provides a mock function with given fields: ctx
func (_m *CommandUc) LocalCommandsDeadlineCronHandler(ctx context.Context) {
	_m.Called(ctx)
}

// OnLocalCancelReservation provides a mock function with given fields: ctx, rq
func (_m *CommandUc) OnLocalCancelReservation(ctx context.Context, rq *domain.Command) error {
	ret := _m.Called(ctx, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnLocalCommandSetResponse provides a mock function with given fields: ctx, uid, status, errMsg
func (_m *CommandUc) OnLocalCommandSetResponse(ctx context.Context, uid string, status string, errMsg string) error {
	ret := _m.Called(ctx, uid, status, errMsg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, uid, status, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnLocalReserve provides a mock function with given fields: ctx, rq
func (_m *CommandUc) OnLocalReserve(ctx context.Context, rq *domain.Command) error {
	ret := _m.Called(ctx, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnLocalStartSession provides a mock function with given fields: ctx, rq
func (_m *CommandUc) OnLocalStartSession(ctx context.Context, rq *domain.Command) error {
	ret := _m.Called(ctx, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnLocalStopSession provides a mock function with given fields: ctx, rq
func (_m *CommandUc) OnLocalStopSession(ctx context.Context, rq *domain.Command) error {
	ret := _m.Called(ctx, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnLocalUnlockConnector provides a mock function with given fields: ctx, rq
func (_m *CommandUc) OnLocalUnlockConnector(ctx context.Context, rq *domain.Command) error {
	ret := _m.Called(ctx, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteCancelReservation provides a mock function with given fields: ctx, platformId, rq
func (_m *CommandUc) OnRemoteCancelReservation(ctx context.Context, platformId string, rq *model.OcpiCancelReservation) (*model.OcpiCommandResponse, error) {
	ret := _m.Called(ctx, platformId, rq)

	var r0 *model.OcpiCommandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiCancelReservation) (*model.OcpiCommandResponse, error)); ok {
		return rf(ctx, platformId, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiCancelReservation) *model.OcpiCommandResponse); ok {
		r0 = rf(ctx, platformId, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCommandResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.OcpiCancelReservation) error); ok {
		r1 = rf(ctx, platformId, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnRemoteReserve provides a mock function with given fields: ctx, platformId, rq
func (_m *CommandUc) OnRemoteReserve(ctx context.Context, platformId string, rq *model.OcpiReserveNow) (*model.OcpiCommandResponse, error) {
	ret := _m.Called(ctx, platformId, rq)

	var r0 *model.OcpiCommandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiReserveNow) (*model.OcpiCommandResponse, error)); ok {
		return rf(ctx, platformId, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiReserveNow) *model.OcpiCommandResponse); ok {
		r0 = rf(ctx, platformId, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCommandResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.OcpiReserveNow) error); ok {
		r1 = rf(ctx, platformId, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnRemoteSetResponse provides a mock function with given fields: ctx, platformId, uid, rq
func (_m *CommandUc) OnRemoteSetResponse(ctx context.Context, platformId string, uid string, rq *model.OcpiCommandResult) error {
	ret := _m.Called(ctx, platformId, uid, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.OcpiCommandResult) error); ok {
		r0 = rf(ctx, platformId, uid, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteStartSession provides a mock function with given fields: ctx, platformId, rq
func (_m *CommandUc) OnRemoteStartSession(ctx context.Context, platformId string, rq *model.OcpiStartSession) (*model.OcpiCommandResponse, error) {
	ret := _m.Called(ctx, platformId, rq)

	var r0 *model.OcpiCommandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiStartSession) (*model.OcpiCommandResponse, error)); ok {
		return rf(ctx, platformId, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiStartSession) *model.OcpiCommandResponse); ok {
		r0 = rf(ctx, platformId, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCommandResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.OcpiStartSession) error); ok {
		r1 = rf(ctx, platformId, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnRemoteStopSession provides a mock function with given fields: ctx, platformId, rq
func (_m *CommandUc) OnRemoteStopSession(ctx context.Context, platformId string, rq *model.OcpiStopSession) (*model.OcpiCommandResponse, error) {
	ret := _m.Called(ctx, platformId, rq)

	var r0 *model.OcpiCommandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiStopSession) (*model.OcpiCommandResponse, error)); ok {
		return rf(ctx, platformId, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiStopSession) *model.OcpiCommandResponse); ok {
		r0 = rf(ctx, platformId, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCommandResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.OcpiStopSession) error); ok {
		r1 = rf(ctx, platformId, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnRemoteUnlockConnector provides a mock function with given fields: ctx, platformId, rq
func (_m *CommandUc) OnRemoteUnlockConnector(ctx context.Context, platformId string, rq *model.OcpiUnlockConnector) (*model.OcpiCommandResponse, error) {
	ret := _m.Called(ctx, platformId, rq)

	var r0 *model.OcpiCommandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiUnlockConnector) (*model.OcpiCommandResponse, error)); ok {
		return rf(ctx, platformId, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiUnlockConnector) *model.OcpiCommandResponse); ok {
		r0 = rf(ctx, platformId, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCommandResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.OcpiUnlockConnector) error); ok {
		r1 = rf(ctx, platformId, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoteCommandsDeadlineCronHandler provides a mock function with given fields: ctx
func (_m *CommandUc) RemoteCommandsDeadlineCronHandler(ctx context.Context) {
	_m.Called(ctx)
}

// NewCommandUc creates a new instance of CommandUc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandUc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandUc {
	mock := &CommandUc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
