// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	model "github.com/mikhailbolshakov/ocpi/model"
)

// CredentialsUc is an autogenerated mock type for the CredentialsUc type
type CredentialsUc struct {
	mock.Mock
}

// AcceptConnection provides a mock function with given fields: ctx, senderPlatformId, rq
func (_m *CredentialsUc) AcceptConnection(ctx context.Context, senderPlatformId string, rq *model.OcpiCredentials) (*model.OcpiCredentials, error) {
	ret := _m.Called(ctx, senderPlatformId, rq)

	var r0 *model.OcpiCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiCredentials) (*model.OcpiCredentials, error)); ok {
		return rf(ctx, senderPlatformId, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiCredentials) *model.OcpiCredentials); ok {
		r0 = rf(ctx, senderPlatformId, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.OcpiCredentials) error); ok {
		r1 = rf(ctx, senderPlatformId, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstablishConnection provides a mock function with given fields: ctx, receiverPlatformId
func (_m *CredentialsUc) EstablishConnection(ctx context.Context, receiverPlatformId string) (*domain.Platform, error) {
	ret := _m.Called(ctx, receiverPlatformId)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Platform, error)); ok {
		return rf(ctx, receiverPlatformId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Platform); ok {
		r0 = rf(ctx, receiverPlatformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, receiverPlatformId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnLocalPartyChanged provides a mock function with given fields: ctx, party
func (_m *CredentialsUc) OnLocalPartyChanged(ctx context.Context, party *domain.Party) error {
	ret := _m.Called(ctx, party)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Party) error); ok {
		r0 = rf(ctx, party)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteDeleteCredentials provides a mock function with given fields: ctx, platformId
func (_m *CredentialsUc) OnRemoteDeleteCredentials(ctx context.Context, platformId string) error {
	ret := _m.Called(ctx, platformId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, platformId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteGetCredentials provides a mock function with given fields: ctx, platformId
func (_m *CredentialsUc) OnRemoteGetCredentials(ctx context.Context, platformId string) (*model.OcpiCredentials, error) {
	ret := _m.Called(ctx, platformId)

	var r0 *model.OcpiCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.OcpiCredentials, error)); ok {
		return rf(ctx, platformId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.OcpiCredentials); ok {
		r0 = rf(ctx, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, platformId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnRemotePartyPull provides a mock function with given fields: ctx
func (_m *CredentialsUc) OnRemotePartyPull(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateConnection provides a mock function with given fields: ctx, receiverPlatformId
func (_m *CredentialsUc) UpdateConnection(ctx context.Context, receiverPlatformId string) (*domain.Platform, error) {
	ret := _m.Called(ctx, receiverPlatformId)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Platform, error)); ok {
		return rf(ctx, receiverPlatformId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Platform); ok {
		r0 = rf(ctx, receiverPlatformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, receiverPlatformId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCredentialsUc creates a new instance of CredentialsUc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialsUc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialsUc {
	mock := &CredentialsUc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
