// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	backend "github.com/mikhailbolshakov/ocpi/backend"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mikhailbolshakov/ocpi/model"
)

// CredentialsConverter is an autogenerated mock type for the CredentialsConverter type
type CredentialsConverter struct {
	mock.Mock
}

// PartiesDomainToBackend provides a mock function with given fields: parties
func (_m *CredentialsConverter) PartiesDomainToBackend(parties []*domain.Party) []*backend.Party {
	ret := _m.Called(parties)

	var r0 []*backend.Party
	if rf, ok := ret.Get(0).(func([]*domain.Party) []*backend.Party); ok {
		r0 = rf(parties)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Party)
		}
	}

	return r0
}

// PartiesDomainToModel provides a mock function with given fields: parties
func (_m *CredentialsConverter) PartiesDomainToModel(parties ...*domain.Party) []*model.OcpiCredentialRole {
	_va := make([]interface{}, len(parties))
	for _i := range parties {
		_va[_i] = parties[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*model.OcpiCredentialRole
	if rf, ok := ret.Get(0).(func(...*domain.Party) []*model.OcpiCredentialRole); ok {
		r0 = rf(parties...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiCredentialRole)
		}
	}

	return r0
}

// PartiesModelToDomain provides a mock function with given fields: platformId, status, roles
func (_m *CredentialsConverter) PartiesModelToDomain(platformId string, status string, roles ...*model.OcpiCredentialRole) []*domain.Party {
	_va := make([]interface{}, len(roles))
	for _i := range roles {
		_va[_i] = roles[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, platformId, status)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*domain.Party
	if rf, ok := ret.Get(0).(func(string, string, ...*model.OcpiCredentialRole) []*domain.Party); ok {
		r0 = rf(platformId, status, roles...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Party)
		}
	}

	return r0
}

// PartyBackendToDomain provides a mock function with given fields: platformId, p
func (_m *CredentialsConverter) PartyBackendToDomain(platformId string, p *backend.Party) *domain.Party {
	ret := _m.Called(platformId, p)

	var r0 *domain.Party
	if rf, ok := ret.Get(0).(func(string, *backend.Party) *domain.Party); ok {
		r0 = rf(platformId, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	return r0
}

// PartyDomainToBackend provides a mock function with given fields: party
func (_m *CredentialsConverter) PartyDomainToBackend(party *domain.Party) *backend.Party {
	ret := _m.Called(party)

	var r0 *backend.Party
	if rf, ok := ret.Get(0).(func(*domain.Party) *backend.Party); ok {
		r0 = rf(party)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Party)
		}
	}

	return r0
}

// PlatformBackendToDomain provides a mock function with given fields: rq
func (_m *CredentialsConverter) PlatformBackendToDomain(rq *backend.PlatformRequest) *domain.Platform {
	ret := _m.Called(rq)

	var r0 *domain.Platform
	if rf, ok := ret.Get(0).(func(*backend.PlatformRequest) *domain.Platform); ok {
		r0 = rf(rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	return r0
}

// PlatformDomainToBackend provides a mock function with given fields: p
func (_m *CredentialsConverter) PlatformDomainToBackend(p *domain.Platform) *backend.Platform {
	ret := _m.Called(p)

	var r0 *backend.Platform
	if rf, ok := ret.Get(0).(func(*domain.Platform) *backend.Platform); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Platform)
		}
	}

	return r0
}

// NewCredentialsConverter creates a new instance of CredentialsConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialsConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialsConverter {
	mock := &CredentialsConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
