// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrorHandler is an autogenerated mock type for the ErrorHandler type
type ErrorHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: err
func (_m *ErrorHandler) Execute(err error) {
	_m.Called(err)
}

// NewErrorHandler creates a new instance of ErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorHandler {
	mock := &ErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
