// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	model "github.com/mikhailbolshakov/ocpi/model"

	time "time"
)

// HubUc is an autogenerated mock type for the HubUc type
type HubUc struct {
	mock.Mock
}

// OnLocalClientInfoChanged provides a mock function with given fields: ctx, party
func (_m *HubUc) OnLocalClientInfoChanged(ctx context.Context, party *domain.Party) error {
	ret := _m.Called(ctx, party)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Party) error); ok {
		r0 = rf(ctx, party)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteClientInfoPut provides a mock function with given fields: ctx, platformId, loc
func (_m *HubUc) OnRemoteClientInfoPut(ctx context.Context, platformId string, loc *model.OcpiClientInfo) error {
	ret := _m.Called(ctx, platformId, loc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiClientInfo) error); ok {
		r0 = rf(ctx, platformId, loc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteClientInfosPull provides a mock function with given fields: ctx, from, to
func (_m *HubUc) OnRemoteClientInfosPull(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteClientInfosPullWhenPushNotSupported provides a mock function with given fields: ctx, from, to
func (_m *HubUc) OnRemoteClientInfosPullWhenPushNotSupported(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHubUc creates a new instance of HubUc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHubUc(t interface {
	mock.TestingT
	Cleanup(func())
}) *HubUc {
	mock := &HubUc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
