// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	model "github.com/mikhailbolshakov/ocpi/model"

	time "time"
)

// LocationUc is an autogenerated mock type for the LocationUc type
type LocationUc struct {
	mock.Mock
}

// OnLocalConnectorChanged provides a mock function with given fields: ctx, con
func (_m *LocationUc) OnLocalConnectorChanged(ctx context.Context, con *domain.Connector) error {
	ret := _m.Called(ctx, con)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Connector) error); ok {
		r0 = rf(ctx, con)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnLocalEvseChanged provides a mock function with given fields: ctx, evse
func (_m *LocationUc) OnLocalEvseChanged(ctx context.Context, evse *domain.Evse) error {
	ret := _m.Called(ctx, evse)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Evse) error); ok {
		r0 = rf(ctx, evse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnLocalEvseStatusChanged provides a mock function with given fields: ctx, locId, evseId, status
func (_m *LocationUc) OnLocalEvseStatusChanged(ctx context.Context, locId string, evseId string, status string) error {
	ret := _m.Called(ctx, locId, evseId, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, locId, evseId, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnLocalLocationChanged provides a mock function with given fields: ctx, loc
func (_m *LocationUc) OnLocalLocationChanged(ctx context.Context, loc *domain.Location) error {
	ret := _m.Called(ctx, loc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Location) error); ok {
		r0 = rf(ctx, loc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteConnectorPatch provides a mock function with given fields: ctx, platformId, locId, evseId, countryCode, partyId, con
func (_m *LocationUc) OnRemoteConnectorPatch(ctx context.Context, platformId string, locId string, evseId string, countryCode string, partyId string, con *model.OcpiConnector) error {
	ret := _m.Called(ctx, platformId, locId, evseId, countryCode, partyId, con)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, *model.OcpiConnector) error); ok {
		r0 = rf(ctx, platformId, locId, evseId, countryCode, partyId, con)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteConnectorPut provides a mock function with given fields: ctx, platformId, locId, evseId, countryCode, partyId, con
func (_m *LocationUc) OnRemoteConnectorPut(ctx context.Context, platformId string, locId string, evseId string, countryCode string, partyId string, con *model.OcpiConnector) error {
	ret := _m.Called(ctx, platformId, locId, evseId, countryCode, partyId, con)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, *model.OcpiConnector) error); ok {
		r0 = rf(ctx, platformId, locId, evseId, countryCode, partyId, con)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteEvsePatch provides a mock function with given fields: ctx, platformId, locId, countryCode, partyId, evse
func (_m *LocationUc) OnRemoteEvsePatch(ctx context.Context, platformId string, locId string, countryCode string, partyId string, evse *model.OcpiEvse) error {
	ret := _m.Called(ctx, platformId, locId, countryCode, partyId, evse)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiEvse) error); ok {
		r0 = rf(ctx, platformId, locId, countryCode, partyId, evse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteEvsePut provides a mock function with given fields: ctx, platformId, locId, countryCode, partyId, evse
func (_m *LocationUc) OnRemoteEvsePut(ctx context.Context, platformId string, locId string, countryCode string, partyId string, evse *model.OcpiEvse) error {
	ret := _m.Called(ctx, platformId, locId, countryCode, partyId, evse)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiEvse) error); ok {
		r0 = rf(ctx, platformId, locId, countryCode, partyId, evse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteLocationPatch provides a mock function with given fields: ctx, platformId, loc
func (_m *LocationUc) OnRemoteLocationPatch(ctx context.Context, platformId string, loc *model.OcpiLocation) error {
	ret := _m.Called(ctx, platformId, loc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiLocation) error); ok {
		r0 = rf(ctx, platformId, loc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteLocationPut provides a mock function with given fields: ctx, platformId, loc
func (_m *LocationUc) OnRemoteLocationPut(ctx context.Context, platformId string, loc *model.OcpiLocation) error {
	ret := _m.Called(ctx, platformId, loc)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiLocation) error); ok {
		r0 = rf(ctx, platformId, loc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteLocationsPull provides a mock function with given fields: ctx, from, to
func (_m *LocationUc) OnRemoteLocationsPull(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteLocationsPullWhenPushNotSupported provides a mock function with given fields: ctx, from, to
func (_m *LocationUc) OnRemoteLocationsPullWhenPushNotSupported(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLocationUc creates a new instance of LocationUc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocationUc(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocationUc {
	mock := &LocationUc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
