// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	ocpi "github.com/mikhailbolshakov/ocpi"
)

// LocalPlatformService is an autogenerated mock type for the LocalPlatformService type
type LocalPlatformService struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx
func (_m *LocalPlatformService) Get(ctx context.Context) (*domain.Platform, error) {
	ret := _m.Called(ctx)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Platform, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Platform); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEndpoints provides a mock function with given fields: ctx, version
func (_m *LocalPlatformService) GetEndpoints(ctx context.Context, version string) domain.ModuleEndpoints {
	ret := _m.Called(ctx, version)

	var r0 domain.ModuleEndpoints
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ModuleEndpoints); ok {
		r0 = rf(ctx, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.ModuleEndpoints)
		}
	}

	return r0
}

// GetPlatformId provides a mock function with given fields: ctx
func (_m *LocalPlatformService) GetPlatformId(ctx context.Context) string {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Init provides a mock function with given fields: ctx, cfg
func (_m *LocalPlatformService) Init(ctx context.Context, cfg *ocpi.CfgOcpiConfig) error {
	ret := _m.Called(ctx, cfg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.CfgOcpiConfig) error); ok {
		r0 = rf(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitializePlatform provides a mock function with given fields: ctx
func (_m *LocalPlatformService) InitializePlatform(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLocalPlatformService creates a new instance of LocalPlatformService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalPlatformService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalPlatformService {
	mock := &LocalPlatformService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
