// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	backend "github.com/mikhailbolshakov/ocpi/backend"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mikhailbolshakov/ocpi/model"
)

// LocationConverter is an autogenerated mock type for the LocationConverter type
type LocationConverter struct {
	mock.Mock
}

// ConnectorBackendToDomain provides a mock function with given fields: con, platformId, locId, evseId
func (_m *LocationConverter) ConnectorBackendToDomain(con *backend.Connector, platformId string, locId string, evseId string) *domain.Connector {
	ret := _m.Called(con, platformId, locId, evseId)

	var r0 *domain.Connector
	if rf, ok := ret.Get(0).(func(*backend.Connector, string, string, string) *domain.Connector); ok {
		r0 = rf(con, platformId, locId, evseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Connector)
		}
	}

	return r0
}

// ConnectorDomainToBackend provides a mock function with given fields: con
func (_m *LocationConverter) ConnectorDomainToBackend(con *domain.Connector) *backend.Connector {
	ret := _m.Called(con)

	var r0 *backend.Connector
	if rf, ok := ret.Get(0).(func(*domain.Connector) *backend.Connector); ok {
		r0 = rf(con)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Connector)
		}
	}

	return r0
}

// ConnectorDomainToModel provides a mock function with given fields: con
func (_m *LocationConverter) ConnectorDomainToModel(con *domain.Connector) *model.OcpiConnector {
	ret := _m.Called(con)

	var r0 *model.OcpiConnector
	if rf, ok := ret.Get(0).(func(*domain.Connector) *model.OcpiConnector); ok {
		r0 = rf(con)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiConnector)
		}
	}

	return r0
}

// ConnectorModelToDomain provides a mock function with given fields: con, cc, partyId, platformId, locId, evseId
func (_m *LocationConverter) ConnectorModelToDomain(con *model.OcpiConnector, cc string, partyId string, platformId string, locId string, evseId string) *domain.Connector {
	ret := _m.Called(con, cc, partyId, platformId, locId, evseId)

	var r0 *domain.Connector
	if rf, ok := ret.Get(0).(func(*model.OcpiConnector, string, string, string, string, string) *domain.Connector); ok {
		r0 = rf(con, cc, partyId, platformId, locId, evseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Connector)
		}
	}

	return r0
}

// ConnectorsDomainToBackend provides a mock function with given fields: cons
func (_m *LocationConverter) ConnectorsDomainToBackend(cons []*domain.Connector) []*backend.Connector {
	ret := _m.Called(cons)

	var r0 []*backend.Connector
	if rf, ok := ret.Get(0).(func([]*domain.Connector) []*backend.Connector); ok {
		r0 = rf(cons)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Connector)
		}
	}

	return r0
}

// ConnectorsDomainToModel provides a mock function with given fields: cons
func (_m *LocationConverter) ConnectorsDomainToModel(cons []*domain.Connector) []*model.OcpiConnector {
	ret := _m.Called(cons)

	var r0 []*model.OcpiConnector
	if rf, ok := ret.Get(0).(func([]*domain.Connector) []*model.OcpiConnector); ok {
		r0 = rf(cons)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiConnector)
		}
	}

	return r0
}

// EvseBackendToDomain provides a mock function with given fields: e, platformId, locId
func (_m *LocationConverter) EvseBackendToDomain(e *backend.Evse, platformId string, locId string) *domain.Evse {
	ret := _m.Called(e, platformId, locId)

	var r0 *domain.Evse
	if rf, ok := ret.Get(0).(func(*backend.Evse, string, string) *domain.Evse); ok {
		r0 = rf(e, platformId, locId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Evse)
		}
	}

	return r0
}

// EvseDomainToBackend provides a mock function with given fields: evse
func (_m *LocationConverter) EvseDomainToBackend(evse *domain.Evse) *backend.Evse {
	ret := _m.Called(evse)

	var r0 *backend.Evse
	if rf, ok := ret.Get(0).(func(*domain.Evse) *backend.Evse); ok {
		r0 = rf(evse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Evse)
		}
	}

	return r0
}

// EvseDomainToModel provides a mock function with given fields: evse
func (_m *LocationConverter) EvseDomainToModel(evse *domain.Evse) *model.OcpiEvse {
	ret := _m.Called(evse)

	var r0 *model.OcpiEvse
	if rf, ok := ret.Get(0).(func(*domain.Evse) *model.OcpiEvse); ok {
		r0 = rf(evse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiEvse)
		}
	}

	return r0
}

// EvseModelToDomain provides a mock function with given fields: e, cc, partyId, platformId, locId
func (_m *LocationConverter) EvseModelToDomain(e *model.OcpiEvse, cc string, partyId string, platformId string, locId string) *domain.Evse {
	ret := _m.Called(e, cc, partyId, platformId, locId)

	var r0 *domain.Evse
	if rf, ok := ret.Get(0).(func(*model.OcpiEvse, string, string, string, string) *domain.Evse); ok {
		r0 = rf(e, cc, partyId, platformId, locId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Evse)
		}
	}

	return r0
}

// EvsesDomainToBackend provides a mock function with given fields: evses
func (_m *LocationConverter) EvsesDomainToBackend(evses []*domain.Evse) []*backend.Evse {
	ret := _m.Called(evses)

	var r0 []*backend.Evse
	if rf, ok := ret.Get(0).(func([]*domain.Evse) []*backend.Evse); ok {
		r0 = rf(evses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Evse)
		}
	}

	return r0
}

// EvsesDomainToModel provides a mock function with given fields: evses
func (_m *LocationConverter) EvsesDomainToModel(evses []*domain.Evse) []*model.OcpiEvse {
	ret := _m.Called(evses)

	var r0 []*model.OcpiEvse
	if rf, ok := ret.Get(0).(func([]*domain.Evse) []*model.OcpiEvse); ok {
		r0 = rf(evses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiEvse)
		}
	}

	return r0
}

// LocationBackendToDomain provides a mock function with given fields: loc, platformId
func (_m *LocationConverter) LocationBackendToDomain(loc *backend.Location, platformId string) *domain.Location {
	ret := _m.Called(loc, platformId)

	var r0 *domain.Location
	if rf, ok := ret.Get(0).(func(*backend.Location, string) *domain.Location); ok {
		r0 = rf(loc, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Location)
		}
	}

	return r0
}

// LocationDomainToBackend provides a mock function with given fields: loc
func (_m *LocationConverter) LocationDomainToBackend(loc *domain.Location) *backend.Location {
	ret := _m.Called(loc)

	var r0 *backend.Location
	if rf, ok := ret.Get(0).(func(*domain.Location) *backend.Location); ok {
		r0 = rf(loc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Location)
		}
	}

	return r0
}

// LocationDomainToModel provides a mock function with given fields: loc
func (_m *LocationConverter) LocationDomainToModel(loc *domain.Location) *model.OcpiLocation {
	ret := _m.Called(loc)

	var r0 *model.OcpiLocation
	if rf, ok := ret.Get(0).(func(*domain.Location) *model.OcpiLocation); ok {
		r0 = rf(loc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiLocation)
		}
	}

	return r0
}

// LocationModelToDomain provides a mock function with given fields: loc, platformId
func (_m *LocationConverter) LocationModelToDomain(loc *model.OcpiLocation, platformId string) *domain.Location {
	ret := _m.Called(loc, platformId)

	var r0 *domain.Location
	if rf, ok := ret.Get(0).(func(*model.OcpiLocation, string) *domain.Location); ok {
		r0 = rf(loc, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Location)
		}
	}

	return r0
}

// LocationsDomainToBackend provides a mock function with given fields: locs
func (_m *LocationConverter) LocationsDomainToBackend(locs []*domain.Location) []*backend.Location {
	ret := _m.Called(locs)

	var r0 []*backend.Location
	if rf, ok := ret.Get(0).(func([]*domain.Location) []*backend.Location); ok {
		r0 = rf(locs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Location)
		}
	}

	return r0
}

// LocationsDomainToModel provides a mock function with given fields: locs
func (_m *LocationConverter) LocationsDomainToModel(locs []*domain.Location) []*model.OcpiLocation {
	ret := _m.Called(locs)

	var r0 []*model.OcpiLocation
	if rf, ok := ret.Get(0).(func([]*domain.Location) []*model.OcpiLocation); ok {
		r0 = rf(locs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiLocation)
		}
	}

	return r0
}

// NewLocationConverter creates a new instance of LocationConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocationConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocationConverter {
	mock := &LocationConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
