// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// MaintenanceUc is an autogenerated mock type for the MaintenanceUc type
type MaintenanceUc struct {
	mock.Mock
}

// DeleteLocalPartyByExt provides a mock function with given fields: ctx, extId
func (_m *MaintenanceUc) DeleteLocalPartyByExt(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMaintenanceUc creates a new instance of MaintenanceUc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMaintenanceUc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MaintenanceUc {
	mock := &MaintenanceUc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
