// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/mikhailbolshakov/ocpi/model"

	serverocpi "github.com/mikhailbolshakov/ocpi"
)

// ocpiRestClient is an autogenerated mock type for the ocpiRestClient type
type ocpiRestClient struct {
	mock.Mock
}

// Close provides a mock function with given fields: ctx
func (_m *ocpiRestClient) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCredentials provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform
func (_m *ocpiRestClient) DeleteCredentials(ctx context.Context, url string, token string, fromPlatform string, toPlatform string) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCdr provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, cdrId
func (_m *ocpiRestClient) GetCdr(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, cdrId string) (*model.OcpiCdr, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, cdrId)

	var r0 *model.OcpiCdr
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*model.OcpiCdr, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, cdrId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *model.OcpiCdr); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, cdrId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCdr)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, cdrId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCdrsPage provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) GetCdrsPage(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiGetPageRequest) ([]*model.OcpiCdr, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 []*model.OcpiCdr
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) ([]*model.OcpiCdr, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) []*model.OcpiCdr); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiCdr)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCon provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, locId, evseId, conId
func (_m *ocpiRestClient) GetCon(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, locId string, evseId string, conId string) (*model.OcpiConnector, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, locId, evseId, conId)

	var r0 *model.OcpiConnector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string) (*model.OcpiConnector, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, locId, evseId, conId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string) *model.OcpiConnector); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, locId, evseId, conId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiConnector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, locId, evseId, conId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCredentials provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform
func (_m *ocpiRestClient) GetCredentials(ctx context.Context, url string, token string, fromPlatform string, toPlatform string) (*model.OcpiCredentials, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform)

	var r0 *model.OcpiCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model.OcpiCredentials, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model.OcpiCredentials); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEvse provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, locId, evseId
func (_m *ocpiRestClient) GetEvse(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, locId string, evseId string) (*model.OcpiEvse, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, locId, evseId)

	var r0 *model.OcpiEvse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) (*model.OcpiEvse, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, locId, evseId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) *model.OcpiEvse); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, locId, evseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiEvse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, locId, evseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHubClientInfo provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) GetHubClientInfo(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiGetPageRequest) ([]*model.OcpiClientInfo, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 []*model.OcpiClientInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) ([]*model.OcpiClientInfo, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) []*model.OcpiClientInfo); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiClientInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocation provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, locId
func (_m *ocpiRestClient) GetLocation(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, locId string) (*model.OcpiLocation, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, locId)

	var r0 *model.OcpiLocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*model.OcpiLocation, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, locId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *model.OcpiLocation); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, locId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiLocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, locId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocationPage provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) GetLocationPage(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiGetPageRequest) ([]*model.OcpiLocation, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 []*model.OcpiLocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) ([]*model.OcpiLocation, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) []*model.OcpiLocation); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiLocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSession provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, sessId
func (_m *ocpiRestClient) GetSession(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, sessId string) (*model.OcpiSession, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, sessId)

	var r0 *model.OcpiSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*model.OcpiSession, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, sessId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *model.OcpiSession); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, sessId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, sessId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSessionPage provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) GetSessionPage(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiGetPageRequest) ([]*model.OcpiSession, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 []*model.OcpiSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) ([]*model.OcpiSession, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) []*model.OcpiSession); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTariff provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, trfId
func (_m *ocpiRestClient) GetTariff(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, trfId string) (*model.OcpiTariff, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, trfId)

	var r0 *model.OcpiTariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*model.OcpiTariff, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, trfId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *model.OcpiTariff); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, trfId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiTariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, trfId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTariffPage provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) GetTariffPage(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiGetPageRequest) ([]*model.OcpiTariff, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 []*model.OcpiTariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) ([]*model.OcpiTariff, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) []*model.OcpiTariff); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiTariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetToken provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, tknId
func (_m *ocpiRestClient) GetToken(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, tknId string) (*model.OcpiToken, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, tknId)

	var r0 *model.OcpiToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*model.OcpiToken, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, tknId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *model.OcpiToken); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, tknId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, tknId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokenPage provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) GetTokenPage(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiGetPageRequest) ([]*model.OcpiToken, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 []*model.OcpiToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) ([]*model.OcpiToken, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) []*model.OcpiToken); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *model.OcpiGetPageRequest) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersionDetails provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform
func (_m *ocpiRestClient) GetVersionDetails(ctx context.Context, url string, token string, fromPlatform string, toPlatform string) (*model.OcpiVersionDetails, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform)

	var r0 *model.OcpiVersionDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model.OcpiVersionDetails, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model.OcpiVersionDetails); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiVersionDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersions provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform
func (_m *ocpiRestClient) GetVersions(ctx context.Context, url string, token string, fromPlatform string, toPlatform string) ([]*model.OcpiVersion, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform)

	var r0 []*model.OcpiVersion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]*model.OcpiVersion, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) []*model.OcpiVersion); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiVersion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields: ctx, config
func (_m *ocpiRestClient) Init(ctx context.Context, config *serverocpi.CfgOcpiRemote) error {
	ret := _m.Called(ctx, config)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *serverocpi.CfgOcpiRemote) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchCon provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq, party, locId, evseId
func (_m *ocpiRestClient) PatchCon(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiConnector, party *model.OcpiPartyId, locId string, evseId string) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq, party, locId, evseId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiConnector, *model.OcpiPartyId, string, string) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq, party, locId, evseId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchEvse provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq, party, locId
func (_m *ocpiRestClient) PatchEvse(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiEvse, party *model.OcpiPartyId, locId string) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq, party, locId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiEvse, *model.OcpiPartyId, string) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq, party, locId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchLocation provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) PatchLocation(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiLocation) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiLocation) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchSession provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, sess
func (_m *ocpiRestClient) PatchSession(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, sess *model.OcpiSession) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiSession) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchTariff provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, trf
func (_m *ocpiRestClient) PatchTariff(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, trf *model.OcpiTariff) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, trf)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiTariff) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, trf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchToken provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, tkn
func (_m *ocpiRestClient) PatchToken(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, tkn *model.OcpiToken) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, tkn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiToken) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, tkn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostCdr provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, cdr
func (_m *ocpiRestClient) PostCdr(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, cdr *model.OcpiCdr) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, cdr)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiCdr) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, cdr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostCommand provides a mock function with given fields: ctx, url, token, cmdType, fromPlatform, toPlatform, cmd
func (_m *ocpiRestClient) PostCommand(ctx context.Context, url string, token string, cmdType string, fromPlatform string, toPlatform string, cmd interface{}) error {
	ret := _m.Called(ctx, url, token, cmdType, fromPlatform, toPlatform, cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, interface{}) error); ok {
		r0 = rf(ctx, url, token, cmdType, fromPlatform, toPlatform, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostCommandResponse provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rs
func (_m *ocpiRestClient) PostCommandResponse(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rs *model.OcpiCommandResult) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rs)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiCommandResult) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostCredentials provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) PostCredentials(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiCredentials) (*model.OcpiCredentials, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 *model.OcpiCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiCredentials) (*model.OcpiCredentials, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiCredentials) *model.OcpiCredentials); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *model.OcpiCredentials) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutClientInfo provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) PutClientInfo(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiClientInfo) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiClientInfo) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutCon provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq, party, locId, evseId
func (_m *ocpiRestClient) PutCon(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiConnector, party *model.OcpiPartyId, locId string, evseId string) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq, party, locId, evseId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiConnector, *model.OcpiPartyId, string, string) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq, party, locId, evseId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutCredentials provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) PutCredentials(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiCredentials) (*model.OcpiCredentials, error) {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 *model.OcpiCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiCredentials) (*model.OcpiCredentials, error)); ok {
		return rf(ctx, url, token, fromPlatform, toPlatform, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiCredentials) *model.OcpiCredentials); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *model.OcpiCredentials) error); ok {
		r1 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutEvse provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq, party, locId
func (_m *ocpiRestClient) PutEvse(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiEvse, party *model.OcpiPartyId, locId string) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq, party, locId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiEvse, *model.OcpiPartyId, string) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq, party, locId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutLocation provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, rq
func (_m *ocpiRestClient) PutLocation(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, rq *model.OcpiLocation) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiLocation) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutSession provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, sess
func (_m *ocpiRestClient) PutSession(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, sess *model.OcpiSession) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiSession) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutTariff provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, trf
func (_m *ocpiRestClient) PutTariff(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, trf *model.OcpiTariff) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, trf)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiTariff) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, trf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutToken provides a mock function with given fields: ctx, url, token, fromPlatform, toPlatform, tkn
func (_m *ocpiRestClient) PutToken(ctx context.Context, url string, token string, fromPlatform string, toPlatform string, tkn *model.OcpiToken) error {
	ret := _m.Called(ctx, url, token, fromPlatform, toPlatform, tkn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *model.OcpiToken) error); ok {
		r0 = rf(ctx, url, token, fromPlatform, toPlatform, tkn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newOcpiRestClient creates a new instance of ocpiRestClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newOcpiRestClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ocpiRestClient {
	mock := &ocpiRestClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
