// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// OcpiLogStorage is an autogenerated mock type for the OcpiLogStorage type
type OcpiLogStorage struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, msg
func (_m *OcpiLogStorage) Save(ctx context.Context, msg *domain.LogMessage) {
	_m.Called(ctx, msg)
}

// SearchLog provides a mock function with given fields: ctx, criteria
func (_m *OcpiLogStorage) SearchLog(ctx context.Context, criteria *domain.SearchLogCriteria) ([]*domain.LogMessage, error) {
	ret := _m.Called(ctx, criteria)

	var r0 []*domain.LogMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SearchLogCriteria) ([]*domain.LogMessage, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SearchLogCriteria) []*domain.LogMessage); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.LogMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.SearchLogCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOcpiLogStorage creates a new instance of OcpiLogStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOcpiLogStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *OcpiLogStorage {
	mock := &OcpiLogStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
