// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	usecase "github.com/mikhailbolshakov/ocpi/usecase"
)

// PageReader is an autogenerated mock type for the PageReader type
type PageReader[R usecase.PageResponse] struct {
	mock.Mock
}

// GetPage provides a mock function with given fields: ctx, rq, pageSize, dateFrom, dateTo
func (_m *PageReader[R]) GetPage(ctx context.Context, rq *usecase.OcpiRepositoryBaseRequest, pageSize int, dateFrom *time.Time, dateTo *time.Time) chan R {
	ret := _m.Called(ctx, rq, pageSize, dateFrom, dateTo)

	var r0 chan R
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest, int, *time.Time, *time.Time) chan R); ok {
		r0 = rf(ctx, rq, pageSize, dateFrom, dateTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan R)
		}
	}

	return r0
}

// NewPageReader creates a new instance of PageReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPageReader[R usecase.PageResponse](t interface {
	mock.TestingT
	Cleanup(func())
}) *PageReader[R] {
	mock := &PageReader[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
