// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PageResponse is an autogenerated mock type for the PageResponse type
type PageResponse struct {
	mock.Mock
}

// NewPageResponse creates a new instance of PageResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPageResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *PageResponse {
	mock := &PageResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
