// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	time "time"
)

// PartyStorage is an autogenerated mock type for the PartyStorage type
type PartyStorage struct {
	mock.Mock
}

// CreateParty provides a mock function with given fields: ctx, party
func (_m *PartyStorage) CreateParty(ctx context.Context, party *domain.Party) error {
	ret := _m.Called(ctx, party)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Party) error); ok {
		r0 = rf(ctx, party)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePartyByExtId provides a mock function with given fields: ctx, extId
func (_m *PartyStorage) DeletePartyByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByRefId provides a mock function with given fields: ctx, refId
func (_m *PartyStorage) GetByRefId(ctx context.Context, refId string) (*domain.Party, error) {
	ret := _m.Called(ctx, refId)

	var r0 *domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Party, error)); ok {
		return rf(ctx, refId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Party); ok {
		r0 = rf(ctx, refId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartiesByPlatform provides a mock function with given fields: ctx, platformId
func (_m *PartyStorage) GetPartiesByPlatform(ctx context.Context, platformId string) ([]*domain.Party, error) {
	ret := _m.Called(ctx, platformId)

	var r0 []*domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Party, error)); ok {
		return rf(ctx, platformId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Party); ok {
		r0 = rf(ctx, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, platformId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParty provides a mock function with given fields: ctx, id
func (_m *PartyStorage) GetParty(ctx context.Context, id string) (*domain.Party, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Party, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Party); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartyByExtId provides a mock function with given fields: ctx, extId
func (_m *PartyStorage) GetPartyByExtId(ctx context.Context, extId domain.PartyExtId) (*domain.Party, error) {
	ret := _m.Called(ctx, extId)

	var r0 *domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) (*domain.Party, error)); ok {
		return rf(ctx, extId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) *domain.Party); ok {
		r0 = rf(ctx, extId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PartyExtId) error); ok {
		r1 = rf(ctx, extId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkSentParties provides a mock function with given fields: ctx, date, partyIds
func (_m *PartyStorage) MarkSentParties(ctx context.Context, date time.Time, partyIds ...string) error {
	_va := make([]interface{}, len(partyIds))
	for _i := range partyIds {
		_va[_i] = partyIds[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, date)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, ...string) error); ok {
		r0 = rf(ctx, date, partyIds...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, criteria
func (_m *PartyStorage) Search(ctx context.Context, criteria *domain.PartySearchCriteria) (*domain.PartySearchResponse, error) {
	ret := _m.Called(ctx, criteria)

	var r0 *domain.PartySearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PartySearchCriteria) (*domain.PartySearchResponse, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PartySearchCriteria) *domain.PartySearchResponse); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PartySearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.PartySearchCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateParty provides a mock function with given fields: ctx, party
func (_m *PartyStorage) UpdateParty(ctx context.Context, party *domain.Party) error {
	ret := _m.Called(ctx, party)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Party) error); ok {
		r0 = rf(ctx, party)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPartyStorage creates a new instance of PartyStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartyStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartyStorage {
	mock := &PartyStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
