// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// PartyService is an autogenerated mock type for the PartyService type
type PartyService struct {
	mock.Mock
}

// DeletePartyByExtId provides a mock function with given fields: ctx, extId
func (_m *PartyService) DeletePartyByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *PartyService) Get(ctx context.Context, id string) (*domain.Party, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Party, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Party); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByExtId provides a mock function with given fields: ctx, extId
func (_m *PartyService) GetByExtId(ctx context.Context, extId domain.PartyExtId) (*domain.Party, error) {
	ret := _m.Called(ctx, extId)

	var r0 *domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) (*domain.Party, error)); ok {
		return rf(ctx, extId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) *domain.Party); ok {
		r0 = rf(ctx, extId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PartyExtId) error); ok {
		r1 = rf(ctx, extId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPlatform provides a mock function with given fields: ctx, platformId
func (_m *PartyService) GetByPlatform(ctx context.Context, platformId string) ([]*domain.Party, error) {
	ret := _m.Called(ctx, platformId)

	var r0 []*domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Party, error)); ok {
		return rf(ctx, platformId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Party); ok {
		r0 = rf(ctx, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, platformId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkSent provides a mock function with given fields: ctx, partyIds
func (_m *PartyService) MarkSent(ctx context.Context, partyIds ...string) error {
	_va := make([]interface{}, len(partyIds))
	for _i := range partyIds {
		_va[_i] = partyIds[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, partyIds...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Merge provides a mock function with given fields: ctx, party
func (_m *PartyService) Merge(ctx context.Context, party *domain.Party) (*domain.Party, error) {
	ret := _m.Called(ctx, party)

	var r0 *domain.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Party) (*domain.Party, error)); ok {
		return rf(ctx, party)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Party) *domain.Party); ok {
		r0 = rf(ctx, party)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Party) error); ok {
		r1 = rf(ctx, party)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergeMany provides a mock function with given fields: ctx, parties
func (_m *PartyService) MergeMany(ctx context.Context, parties ...*domain.Party) error {
	_va := make([]interface{}, len(parties))
	for _i := range parties {
		_va[_i] = parties[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...*domain.Party) error); ok {
		r0 = rf(ctx, parties...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, cr
func (_m *PartyService) Search(ctx context.Context, cr *domain.PartySearchCriteria) (*domain.PartySearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.PartySearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PartySearchCriteria) (*domain.PartySearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PartySearchCriteria) *domain.PartySearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PartySearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.PartySearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPartyService creates a new instance of PartyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartyService {
	mock := &PartyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
