// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// PlatformStorage is an autogenerated mock type for the PlatformStorage type
type PlatformStorage struct {
	mock.Mock
}

// CreatePlatform provides a mock function with given fields: ctx, p
func (_m *PlatformStorage) CreatePlatform(ctx context.Context, p *domain.Platform) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Platform) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePlatform provides a mock function with given fields: ctx, p
func (_m *PlatformStorage) DeletePlatform(ctx context.Context, p *domain.Platform) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Platform) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPlatform provides a mock function with given fields: ctx, id
func (_m *PlatformStorage) GetPlatform(ctx context.Context, id string) (*domain.Platform, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Platform, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Platform); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlatformByTokenA provides a mock function with given fields: ctx, tokenA
func (_m *PlatformStorage) GetPlatformByTokenA(ctx context.Context, tokenA domain.PlatformToken) (*domain.Platform, error) {
	ret := _m.Called(ctx, tokenA)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) (*domain.Platform, error)); ok {
		return rf(ctx, tokenA)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) *domain.Platform); ok {
		r0 = rf(ctx, tokenA)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PlatformToken) error); ok {
		r1 = rf(ctx, tokenA)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlatformByTokenB provides a mock function with given fields: ctx, token
func (_m *PlatformStorage) GetPlatformByTokenB(ctx context.Context, token domain.PlatformToken) (*domain.Platform, error) {
	ret := _m.Called(ctx, token)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) (*domain.Platform, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) *domain.Platform); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PlatformToken) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlatformByTokenC provides a mock function with given fields: ctx, token
func (_m *PlatformStorage) GetPlatformByTokenC(ctx context.Context, token domain.PlatformToken) (*domain.Platform, error) {
	ret := _m.Called(ctx, token)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) (*domain.Platform, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) *domain.Platform); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PlatformToken) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchPlatforms provides a mock function with given fields: ctx, cr
func (_m *PlatformStorage) SearchPlatforms(ctx context.Context, cr *domain.PlatformSearchCriteria) ([]*domain.Platform, error) {
	ret := _m.Called(ctx, cr)

	var r0 []*domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PlatformSearchCriteria) ([]*domain.Platform, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PlatformSearchCriteria) []*domain.Platform); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.PlatformSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePlatform provides a mock function with given fields: ctx, p
func (_m *PlatformStorage) UpdatePlatform(ctx context.Context, p *domain.Platform) error {
	ret := _m.Called(ctx, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Platform) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPlatformStorage creates a new instance of PlatformStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlatformStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlatformStorage {
	mock := &PlatformStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
