// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	ocpi "github.com/mikhailbolshakov/ocpi"
)

// PlatformService is an autogenerated mock type for the PlatformService type
type PlatformService struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, platformId
func (_m *PlatformService) Get(ctx context.Context, platformId string) (*domain.Platform, error) {
	ret := _m.Called(ctx, platformId)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Platform, error)); ok {
		return rf(ctx, platformId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Platform); ok {
		r0 = rf(ctx, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, platformId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTokenA provides a mock function with given fields: ctx, token
func (_m *PlatformService) GetByTokenA(ctx context.Context, token domain.PlatformToken) (*domain.Platform, error) {
	ret := _m.Called(ctx, token)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) (*domain.Platform, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) *domain.Platform); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PlatformToken) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTokenB provides a mock function with given fields: ctx, token
func (_m *PlatformService) GetByTokenB(ctx context.Context, token domain.PlatformToken) (*domain.Platform, error) {
	ret := _m.Called(ctx, token)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) (*domain.Platform, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) *domain.Platform); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PlatformToken) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTokenC provides a mock function with given fields: ctx, token
func (_m *PlatformService) GetByTokenC(ctx context.Context, token domain.PlatformToken) (*domain.Platform, error) {
	ret := _m.Called(ctx, token)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) (*domain.Platform, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PlatformToken) *domain.Platform); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PlatformToken) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields: ctx, cfg
func (_m *PlatformService) Init(ctx context.Context, cfg *ocpi.CfgOcpiConfig) error {
	ret := _m.Called(ctx, cfg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.CfgOcpiConfig) error); ok {
		r0 = rf(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Merge provides a mock function with given fields: ctx, platform
func (_m *PlatformService) Merge(ctx context.Context, platform *domain.Platform) (*domain.Platform, error) {
	ret := _m.Called(ctx, platform)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Platform) (*domain.Platform, error)); ok {
		return rf(ctx, platform)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Platform) *domain.Platform); ok {
		r0 = rf(ctx, platform)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Platform) error); ok {
		r1 = rf(ctx, platform)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleEndpoint provides a mock function with given fields: ctx, platform, module, role
func (_m *PlatformService) RoleEndpoint(ctx context.Context, platform *domain.Platform, module string, role string) domain.Endpoint {
	ret := _m.Called(ctx, platform, module, role)

	var r0 domain.Endpoint
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Platform, string, string) domain.Endpoint); ok {
		r0 = rf(ctx, platform, module, role)
	} else {
		r0 = ret.Get(0).(domain.Endpoint)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, cr
func (_m *PlatformService) Search(ctx context.Context, cr *domain.PlatformSearchCriteria) ([]*domain.Platform, error) {
	ret := _m.Called(ctx, cr)

	var r0 []*domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PlatformSearchCriteria) ([]*domain.Platform, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PlatformSearchCriteria) []*domain.Platform); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.PlatformSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetStatus provides a mock function with given fields: ctx, platformId, status
func (_m *PlatformService) SetStatus(ctx context.Context, platformId string, status string) (*domain.Platform, error) {
	ret := _m.Called(ctx, platformId, status)

	var r0 *domain.Platform
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Platform, error)); ok {
		return rf(ctx, platformId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Platform); ok {
		r0 = rf(ctx, platformId, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Platform)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, platformId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlatformService creates a new instance of PlatformService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlatformService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlatformService {
	mock := &PlatformService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
