// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	model "github.com/mikhailbolshakov/ocpi/model"

	usecase "github.com/mikhailbolshakov/ocpi/usecase"
)

// RemotePlatformRepository is an autogenerated mock type for the RemotePlatformRepository type
type RemotePlatformRepository struct {
	mock.Mock
}

// DeleteCredentials provides a mock function with given fields: ctx, rq
func (_m *RemotePlatformRepository) DeleteCredentials(ctx context.Context, rq *usecase.OcpiRepositoryBaseRequest) error {
	ret := _m.Called(ctx, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) error); ok {
		r0 = rf(ctx, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCredentials provides a mock function with given fields: ctx, rq
func (_m *RemotePlatformRepository) GetCredentials(ctx context.Context, rq *usecase.OcpiRepositoryBaseRequest) (*model.OcpiCredentials, error) {
	ret := _m.Called(ctx, rq)

	var r0 *model.OcpiCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) (*model.OcpiCredentials, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) *model.OcpiCredentials); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersionDetails provides a mock function with given fields: ctx, rq
func (_m *RemotePlatformRepository) GetVersionDetails(ctx context.Context, rq *usecase.OcpiRepositoryBaseRequest) (domain.ModuleEndpoints, error) {
	ret := _m.Called(ctx, rq)

	var r0 domain.ModuleEndpoints
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) (domain.ModuleEndpoints, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) domain.ModuleEndpoints); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.ModuleEndpoints)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVersions provides a mock function with given fields: ctx, rq
func (_m *RemotePlatformRepository) GetVersions(ctx context.Context, rq *usecase.OcpiRepositoryBaseRequest) (domain.Versions, error) {
	ret := _m.Called(ctx, rq)

	var r0 domain.Versions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) (domain.Versions, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) domain.Versions); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Versions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryBaseRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostCredentials provides a mock function with given fields: ctx, rq
func (_m *RemotePlatformRepository) PostCredentials(ctx context.Context, rq *usecase.OcpiRepositoryRequestG[*model.OcpiCredentials]) (*model.OcpiCredentials, error) {
	ret := _m.Called(ctx, rq)

	var r0 *model.OcpiCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryRequestG[*model.OcpiCredentials]) (*model.OcpiCredentials, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryRequestG[*model.OcpiCredentials]) *model.OcpiCredentials); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryRequestG[*model.OcpiCredentials]) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutCredentials provides a mock function with given fields: ctx, rq
func (_m *RemotePlatformRepository) PutCredentials(ctx context.Context, rq *usecase.OcpiRepositoryRequestG[*model.OcpiCredentials]) (*model.OcpiCredentials, error) {
	ret := _m.Called(ctx, rq)

	var r0 *model.OcpiCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryRequestG[*model.OcpiCredentials]) (*model.OcpiCredentials, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryRequestG[*model.OcpiCredentials]) *model.OcpiCredentials); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryRequestG[*model.OcpiCredentials]) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRemotePlatformRepository creates a new instance of RemotePlatformRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemotePlatformRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemotePlatformRepository {
	mock := &RemotePlatformRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
