// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	ocpi "github.com/mikhailbolshakov/ocpi/proto"
)

// RemotePullServiceServer is an autogenerated mock type for the RemotePullServiceServer type
type RemotePullServiceServer struct {
	mock.Mock
}

// PullCdrs provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullCdrs(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullCdrsWhenPushNotSupported provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullCdrsWhenPushNotSupported(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullHubClientInfo provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullHubClientInfo(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullHubClientInfoWhenPushNotSupported provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullHubClientInfoWhenPushNotSupported(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullLocations provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullLocations(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullLocationsWhenPushNotSupported provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullLocationsWhenPushNotSupported(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullParties provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullParties(_a0 context.Context, _a1 *ocpi.EmptyRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.EmptyRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.EmptyRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.EmptyRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullSessions provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullSessions(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullSessionsWhenPushNotSupported provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullSessionsWhenPushNotSupported(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullTariffs provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullTariffs(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullTariffsWhenPushNotSupported provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullTariffsWhenPushNotSupported(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullTokens provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullTokens(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullTokensWhenPushNotSupported provides a mock function with given fields: _a0, _a1
func (_m *RemotePullServiceServer) PullTokensWhenPushNotSupported(_a0 context.Context, _a1 *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) (*ocpi.EmptyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest) *ocpi.EmptyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedRemotePullServiceServer provides a mock function with given fields:
func (_m *RemotePullServiceServer) mustEmbedUnimplementedRemotePullServiceServer() {
	_m.Called()
}

// NewRemotePullServiceServer creates a new instance of RemotePullServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemotePullServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemotePullServiceServer {
	mock := &RemotePullServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
