// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/mikhailbolshakov/ocpi/model"

	usecase "github.com/mikhailbolshakov/ocpi/usecase"
)

// RemoteSessionRepository is an autogenerated mock type for the RemoteSessionRepository type
type RemoteSessionRepository struct {
	mock.Mock
}

// GetSession provides a mock function with given fields: ctx, rq
func (_m *RemoteSessionRepository) GetSession(ctx context.Context, rq *usecase.OcpiRepositoryIdRequest) (*model.OcpiSession, error) {
	ret := _m.Called(ctx, rq)

	var r0 *model.OcpiSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) (*model.OcpiSession, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) *model.OcpiSession); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryIdRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSessions provides a mock function with given fields: ctx, rq
func (_m *RemoteSessionRepository) GetSessions(ctx context.Context, rq *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiSession, error) {
	ret := _m.Called(ctx, rq)

	var r0 []*model.OcpiSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiSession, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) []*model.OcpiSession); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchSessionAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteSessionRepository) PatchSessionAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiSession]) {
	_m.Called(ctx, rq)
}

// PutSessionAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteSessionRepository) PutSessionAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiSession]) {
	_m.Called(ctx, rq)
}

// NewRemoteSessionRepository creates a new instance of RemoteSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteSessionRepository {
	mock := &RemoteSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
