// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	ocpi "github.com/mikhailbolshakov/ocpi/proto"
)

// RemotePullServiceClient is an autogenerated mock type for the RemotePullServiceClient type
type RemotePullServiceClient struct {
	mock.Mock
}

// PullCdrs provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullCdrs(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullCdrsWhenPushNotSupported provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullCdrsWhenPushNotSupported(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullHubClientInfo provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullHubClientInfo(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullHubClientInfoWhenPushNotSupported provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullHubClientInfoWhenPushNotSupported(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullLocations provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullLocations(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullLocationsWhenPushNotSupported provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullLocationsWhenPushNotSupported(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullParties provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullParties(ctx context.Context, in *ocpi.EmptyRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.EmptyRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.EmptyRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.EmptyRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullSessions provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullSessions(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullSessionsWhenPushNotSupported provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullSessionsWhenPushNotSupported(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullTariffs provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullTariffs(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullTariffsWhenPushNotSupported provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullTariffsWhenPushNotSupported(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullTokens provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullTokens(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullTokensWhenPushNotSupported provides a mock function with given fields: ctx, in, opts
func (_m *RemotePullServiceClient) PullTokensWhenPushNotSupported(ctx context.Context, in *ocpi.RemotePullRequest, opts ...grpc.CallOption) (*ocpi.EmptyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ocpi.EmptyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) (*ocpi.EmptyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) *ocpi.EmptyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ocpi.EmptyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ocpi.RemotePullRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRemotePullServiceClient creates a new instance of RemotePullServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemotePullServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemotePullServiceClient {
	mock := &RemotePullServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
