// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/mikhailbolshakov/ocpi/model"

	usecase "github.com/mikhailbolshakov/ocpi/usecase"
)

// RemoteTariffRepository is an autogenerated mock type for the RemoteTariffRepository type
type RemoteTariffRepository struct {
	mock.Mock
}

// GetTariff provides a mock function with given fields: ctx, rq
func (_m *RemoteTariffRepository) GetTariff(ctx context.Context, rq *usecase.OcpiRepositoryIdRequest) (*model.OcpiTariff, error) {
	ret := _m.Called(ctx, rq)

	var r0 *model.OcpiTariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) (*model.OcpiTariff, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) *model.OcpiTariff); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiTariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryIdRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTariffs provides a mock function with given fields: ctx, rq
func (_m *RemoteTariffRepository) GetTariffs(ctx context.Context, rq *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiTariff, error) {
	ret := _m.Called(ctx, rq)

	var r0 []*model.OcpiTariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiTariff, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) []*model.OcpiTariff); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiTariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchTariffAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteTariffRepository) PatchTariffAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiTariff]) {
	_m.Called(ctx, rq)
}

// PutTariffAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteTariffRepository) PutTariffAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiTariff]) {
	_m.Called(ctx, rq)
}

// NewRemoteTariffRepository creates a new instance of RemoteTariffRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteTariffRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteTariffRepository {
	mock := &RemoteTariffRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
