// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/mikhailbolshakov/ocpi/model"

	usecase "github.com/mikhailbolshakov/ocpi/usecase"
)

// RemoteTokenRepository is an autogenerated mock type for the RemoteTokenRepository type
type RemoteTokenRepository struct {
	mock.Mock
}

// GetToken provides a mock function with given fields: ctx, rq
func (_m *RemoteTokenRepository) GetToken(ctx context.Context, rq *usecase.OcpiRepositoryIdRequest) (*model.OcpiToken, error) {
	ret := _m.Called(ctx, rq)

	var r0 *model.OcpiToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) (*model.OcpiToken, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) *model.OcpiToken); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryIdRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTokens provides a mock function with given fields: ctx, rq
func (_m *RemoteTokenRepository) GetTokens(ctx context.Context, rq *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiToken, error) {
	ret := _m.Called(ctx, rq)

	var r0 []*model.OcpiToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiToken, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) []*model.OcpiToken); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchTokenAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteTokenRepository) PatchTokenAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiToken]) {
	_m.Called(ctx, rq)
}

// PutTokenAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteTokenRepository) PutTokenAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiToken]) {
	_m.Called(ctx, rq)
}

// NewRemoteTokenRepository creates a new instance of RemoteTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteTokenRepository {
	mock := &RemoteTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
