// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/mikhailbolshakov/ocpi/model"

	usecase "github.com/mikhailbolshakov/ocpi/usecase"
)

// RemoteCdrRepository is an autogenerated mock type for the RemoteCdrRepository type
type RemoteCdrRepository struct {
	mock.Mock
}

// GetCdr provides a mock function with given fields: ctx, rq
func (_m *RemoteCdrRepository) GetCdr(ctx context.Context, rq *usecase.OcpiRepositoryIdRequest) (*model.OcpiCdr, error) {
	ret := _m.Called(ctx, rq)

	var r0 *model.OcpiCdr
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) (*model.OcpiCdr, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) *model.OcpiCdr); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiCdr)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryIdRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCdrs provides a mock function with given fields: ctx, rq
func (_m *RemoteCdrRepository) GetCdrs(ctx context.Context, rq *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiCdr, error) {
	ret := _m.Called(ctx, rq)

	var r0 []*model.OcpiCdr
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiCdr, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) []*model.OcpiCdr); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiCdr)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostCdrAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteCdrRepository) PostCdrAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiCdr]) {
	_m.Called(ctx, rq)
}

// NewRemoteCdrRepository creates a new instance of RemoteCdrRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteCdrRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteCdrRepository {
	mock := &RemoteCdrRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
