// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/mikhailbolshakov/ocpi/model"

	usecase "github.com/mikhailbolshakov/ocpi/usecase"
)

// RemoteHubClientInfoRepository is an autogenerated mock type for the RemoteHubClientInfoRepository type
type RemoteHubClientInfoRepository struct {
	mock.Mock
}

// GetClientInfos provides a mock function with given fields: ctx, rq
func (_m *RemoteHubClientInfoRepository) GetClientInfos(ctx context.Context, rq *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiClientInfo, error) {
	ret := _m.Called(ctx, rq)

	var r0 []*model.OcpiClientInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiClientInfo, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) []*model.OcpiClientInfo); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiClientInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutClientInfo provides a mock function with given fields: ctx, rq
func (_m *RemoteHubClientInfoRepository) PutClientInfo(ctx context.Context, rq *usecase.OcpiRepositoryRequestG[*model.OcpiClientInfo]) error {
	ret := _m.Called(ctx, rq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryRequestG[*model.OcpiClientInfo]) error); ok {
		r0 = rf(ctx, rq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutClientInfoAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteHubClientInfoRepository) PutClientInfoAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiClientInfo]) {
	_m.Called(ctx, rq)
}

// NewRemoteHubClientInfoRepository creates a new instance of RemoteHubClientInfoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteHubClientInfoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteHubClientInfoRepository {
	mock := &RemoteHubClientInfoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
