// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/mikhailbolshakov/ocpi/model"

	usecase "github.com/mikhailbolshakov/ocpi/usecase"
)

// RemoteLocationRepository is an autogenerated mock type for the RemoteLocationRepository type
type RemoteLocationRepository struct {
	mock.Mock
}

// GetConnector provides a mock function with given fields: ctx, rq, locId, evseId, conId
func (_m *RemoteLocationRepository) GetConnector(ctx context.Context, rq *usecase.OcpiRepositoryBaseRequest, locId string, evseId string, conId string) (*model.OcpiConnector, error) {
	ret := _m.Called(ctx, rq, locId, evseId, conId)

	var r0 *model.OcpiConnector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest, string, string, string) (*model.OcpiConnector, error)); ok {
		return rf(ctx, rq, locId, evseId, conId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest, string, string, string) *model.OcpiConnector); ok {
		r0 = rf(ctx, rq, locId, evseId, conId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiConnector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryBaseRequest, string, string, string) error); ok {
		r1 = rf(ctx, rq, locId, evseId, conId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEvse provides a mock function with given fields: ctx, rq, locId, evseId
func (_m *RemoteLocationRepository) GetEvse(ctx context.Context, rq *usecase.OcpiRepositoryBaseRequest, locId string, evseId string) (*model.OcpiEvse, error) {
	ret := _m.Called(ctx, rq, locId, evseId)

	var r0 *model.OcpiEvse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest, string, string) (*model.OcpiEvse, error)); ok {
		return rf(ctx, rq, locId, evseId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryBaseRequest, string, string) *model.OcpiEvse); ok {
		r0 = rf(ctx, rq, locId, evseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiEvse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryBaseRequest, string, string) error); ok {
		r1 = rf(ctx, rq, locId, evseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocation provides a mock function with given fields: ctx, rq
func (_m *RemoteLocationRepository) GetLocation(ctx context.Context, rq *usecase.OcpiRepositoryIdRequest) (*model.OcpiLocation, error) {
	ret := _m.Called(ctx, rq)

	var r0 *model.OcpiLocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) (*model.OcpiLocation, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryIdRequest) *model.OcpiLocation); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiLocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryIdRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocations provides a mock function with given fields: ctx, rq
func (_m *RemoteLocationRepository) GetLocations(ctx context.Context, rq *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiLocation, error) {
	ret := _m.Called(ctx, rq)

	var r0 []*model.OcpiLocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) ([]*model.OcpiLocation, error)); ok {
		return rf(ctx, rq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) []*model.OcpiLocation); ok {
		r0 = rf(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiLocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.OcpiRepositoryPagingRequest) error); ok {
		r1 = rf(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchConnectorAsync provides a mock function with given fields: ctx, rq, party, evseId, locId
func (_m *RemoteLocationRepository) PatchConnectorAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiConnector], party *model.OcpiPartyId, evseId string, locId string) {
	_m.Called(ctx, rq, party, evseId, locId)
}

// PatchEvseAsync provides a mock function with given fields: ctx, rq, party, locId
func (_m *RemoteLocationRepository) PatchEvseAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiEvse], party *model.OcpiPartyId, locId string) {
	_m.Called(ctx, rq, party, locId)
}

// PatchLocationAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteLocationRepository) PatchLocationAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiLocation]) {
	_m.Called(ctx, rq)
}

// PutConnectorAsync provides a mock function with given fields: ctx, rq, party, evseId, locId
func (_m *RemoteLocationRepository) PutConnectorAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiConnector], party *model.OcpiPartyId, evseId string, locId string) {
	_m.Called(ctx, rq, party, evseId, locId)
}

// PutEvseAsync provides a mock function with given fields: ctx, rq, party, locId
func (_m *RemoteLocationRepository) PutEvseAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiEvse], party *model.OcpiPartyId, locId string) {
	_m.Called(ctx, rq, party, locId)
}

// PutLocationAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteLocationRepository) PutLocationAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiLocation]) {
	_m.Called(ctx, rq)
}

// NewRemoteLocationRepository creates a new instance of RemoteLocationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteLocationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteLocationRepository {
	mock := &RemoteLocationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
