// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/mikhailbolshakov/ocpi/model"

	usecase "github.com/mikhailbolshakov/ocpi/usecase"
)

// RemoteCommandRepository is an autogenerated mock type for the RemoteCommandRepository type
type RemoteCommandRepository struct {
	mock.Mock
}

// PostCommandAsync provides a mock function with given fields: ctx, rq, cmdType, cmd
func (_m *RemoteCommandRepository) PostCommandAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequest, cmdType string, cmd interface{}) {
	_m.Called(ctx, rq, cmdType, cmd)
}

// PostCommandResponseAsync provides a mock function with given fields: ctx, rq
func (_m *RemoteCommandRepository) PostCommandResponseAsync(ctx context.Context, rq *usecase.OcpiRepositoryErrHandlerRequestG[*model.OcpiCommandResult]) {
	_m.Called(ctx, rq)
}

// NewRemoteCommandRepository creates a new instance of RemoteCommandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteCommandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteCommandRepository {
	mock := &RemoteCommandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
