// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// SessionService is an autogenerated mock type for the SessionService type
type SessionService struct {
	mock.Mock
}

// DeleteSessionsByExtId provides a mock function with given fields: ctx, extId
func (_m *SessionService) DeleteSessionsByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSession provides a mock function with given fields: ctx, sessId
func (_m *SessionService) GetSession(ctx context.Context, sessId string) (*domain.Session, error) {
	ret := _m.Called(ctx, sessId)

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return rf(ctx, sessId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = rf(ctx, sessId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSessionWithPeriods provides a mock function with given fields: ctx, sessId
func (_m *SessionService) GetSessionWithPeriods(ctx context.Context, sessId string) (*domain.Session, error) {
	ret := _m.Called(ctx, sessId)

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return rf(ctx, sessId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = rf(ctx, sessId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergeSession provides a mock function with given fields: ctx, sess
func (_m *SessionService) MergeSession(ctx context.Context, sess *domain.Session) (*domain.Session, error) {
	ret := _m.Called(ctx, sess)

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) (*domain.Session, error)); ok {
		return rf(ctx, sess)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) *domain.Session); ok {
		r0 = rf(ctx, sess)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Session) error); ok {
		r1 = rf(ctx, sess)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutSession provides a mock function with given fields: ctx, sess
func (_m *SessionService) PutSession(ctx context.Context, sess *domain.Session) (*domain.Session, error) {
	ret := _m.Called(ctx, sess)

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) (*domain.Session, error)); ok {
		return rf(ctx, sess)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) *domain.Session); ok {
		r0 = rf(ctx, sess)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Session) error); ok {
		r1 = rf(ctx, sess)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchSessions provides a mock function with given fields: ctx, cr
func (_m *SessionService) SearchSessions(ctx context.Context, cr *domain.SessionSearchCriteria) (*domain.SessionSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.SessionSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SessionSearchCriteria) (*domain.SessionSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SessionSearchCriteria) *domain.SessionSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SessionSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.SessionSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSessionService creates a new instance of SessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionService {
	mock := &SessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
