// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	model "github.com/mikhailbolshakov/ocpi/model"

	time "time"
)

// SessionUc is an autogenerated mock type for the SessionUc type
type SessionUc struct {
	mock.Mock
}

// OnLocalSessionChanged provides a mock function with given fields: ctx, sess
func (_m *SessionUc) OnLocalSessionChanged(ctx context.Context, sess *domain.Session) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnLocalSessionPatched provides a mock function with given fields: ctx, sess
func (_m *SessionUc) OnLocalSessionPatched(ctx context.Context, sess *domain.Session) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteSessionPatch provides a mock function with given fields: ctx, platformId, sess
func (_m *SessionUc) OnRemoteSessionPatch(ctx context.Context, platformId string, sess *model.OcpiSession) error {
	ret := _m.Called(ctx, platformId, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiSession) error); ok {
		r0 = rf(ctx, platformId, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteSessionPut provides a mock function with given fields: ctx, platformId, sess
func (_m *SessionUc) OnRemoteSessionPut(ctx context.Context, platformId string, sess *model.OcpiSession) error {
	ret := _m.Called(ctx, platformId, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiSession) error); ok {
		r0 = rf(ctx, platformId, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteSessionsPull provides a mock function with given fields: ctx, from, to
func (_m *SessionUc) OnRemoteSessionsPull(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteSessionsPullWhenPushNotSupported provides a mock function with given fields: ctx, from, to
func (_m *SessionUc) OnRemoteSessionsPullWhenPushNotSupported(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionUc creates a new instance of SessionUc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionUc(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionUc {
	mock := &SessionUc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
