// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// SessionStorage is an autogenerated mock type for the SessionStorage type
type SessionStorage struct {
	mock.Mock
}

// CreateChargingPeriods provides a mock function with given fields: ctx, sess, periods
func (_m *SessionStorage) CreateChargingPeriods(ctx context.Context, sess *domain.Session, periods []*domain.ChargingPeriod) error {
	ret := _m.Called(ctx, sess, periods)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session, []*domain.ChargingPeriod) error); ok {
		r0 = rf(ctx, sess, periods)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSessionsByExtId provides a mock function with given fields: ctx, extId
func (_m *SessionStorage) DeleteSessionsByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChargingPeriods provides a mock function with given fields: ctx, sessIds
func (_m *SessionStorage) GetChargingPeriods(ctx context.Context, sessIds ...string) (map[string][]*domain.ChargingPeriod, error) {
	_va := make([]interface{}, len(sessIds))
	for _i := range sessIds {
		_va[_i] = sessIds[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 map[string][]*domain.ChargingPeriod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) (map[string][]*domain.ChargingPeriod, error)); ok {
		return rf(ctx, sessIds...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...string) map[string][]*domain.ChargingPeriod); ok {
		r0 = rf(ctx, sessIds...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]*domain.ChargingPeriod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = rf(ctx, sessIds...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSession provides a mock function with given fields: ctx, sessId, withChargingPeriods
func (_m *SessionStorage) GetSession(ctx context.Context, sessId string, withChargingPeriods bool) (*domain.Session, error) {
	ret := _m.Called(ctx, sessId, withChargingPeriods)

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*domain.Session, error)); ok {
		return rf(ctx, sessId, withChargingPeriods)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *domain.Session); ok {
		r0 = rf(ctx, sessId, withChargingPeriods)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, sessId, withChargingPeriods)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergeSession provides a mock function with given fields: ctx, sess
func (_m *SessionStorage) MergeSession(ctx context.Context, sess *domain.Session) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchSessions provides a mock function with given fields: ctx, cr
func (_m *SessionStorage) SearchSessions(ctx context.Context, cr *domain.SessionSearchCriteria) (*domain.SessionSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.SessionSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SessionSearchCriteria) (*domain.SessionSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SessionSearchCriteria) *domain.SessionSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SessionSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.SessionSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChargingPeriods provides a mock function with given fields: ctx, sess, periods
func (_m *SessionStorage) UpdateChargingPeriods(ctx context.Context, sess *domain.Session, periods []*domain.ChargingPeriod) error {
	ret := _m.Called(ctx, sess, periods)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session, []*domain.ChargingPeriod) error); ok {
		r0 = rf(ctx, sess, periods)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSession provides a mock function with given fields: ctx, sess
func (_m *SessionStorage) UpdateSession(ctx context.Context, sess *domain.Session) error {
	ret := _m.Called(ctx, sess)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionStorage creates a new instance of SessionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionStorage {
	mock := &SessionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
