// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	backend "github.com/mikhailbolshakov/ocpi/backend"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mikhailbolshakov/ocpi/model"
)

// SessionConverter is an autogenerated mock type for the SessionConverter type
type SessionConverter struct {
	mock.Mock
}

// SessionBackendToDomain provides a mock function with given fields: sess, platformId
func (_m *SessionConverter) SessionBackendToDomain(sess *backend.Session, platformId string) *domain.Session {
	ret := _m.Called(sess, platformId)

	var r0 *domain.Session
	if rf, ok := ret.Get(0).(func(*backend.Session, string) *domain.Session); ok {
		r0 = rf(sess, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	return r0
}

// SessionDomainToBackend provides a mock function with given fields: sess
func (_m *SessionConverter) SessionDomainToBackend(sess *domain.Session) *backend.Session {
	ret := _m.Called(sess)

	var r0 *backend.Session
	if rf, ok := ret.Get(0).(func(*domain.Session) *backend.Session); ok {
		r0 = rf(sess)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Session)
		}
	}

	return r0
}

// SessionDomainToModel provides a mock function with given fields: sess
func (_m *SessionConverter) SessionDomainToModel(sess *domain.Session) *model.OcpiSession {
	ret := _m.Called(sess)

	var r0 *model.OcpiSession
	if rf, ok := ret.Get(0).(func(*domain.Session) *model.OcpiSession); ok {
		r0 = rf(sess)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiSession)
		}
	}

	return r0
}

// SessionModelToDomain provides a mock function with given fields: sess, platformId
func (_m *SessionConverter) SessionModelToDomain(sess *model.OcpiSession, platformId string) *domain.Session {
	ret := _m.Called(sess, platformId)

	var r0 *domain.Session
	if rf, ok := ret.Get(0).(func(*model.OcpiSession, string) *domain.Session); ok {
		r0 = rf(sess, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	return r0
}

// SessionsDomainToBackend provides a mock function with given fields: ts
func (_m *SessionConverter) SessionsDomainToBackend(ts []*domain.Session) []*backend.Session {
	ret := _m.Called(ts)

	var r0 []*backend.Session
	if rf, ok := ret.Get(0).(func([]*domain.Session) []*backend.Session); ok {
		r0 = rf(ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Session)
		}
	}

	return r0
}

// SessionsDomainToModel provides a mock function with given fields: ts
func (_m *SessionConverter) SessionsDomainToModel(ts []*domain.Session) []*model.OcpiSession {
	ret := _m.Called(ts)

	var r0 []*model.OcpiSession
	if rf, ok := ret.Get(0).(func([]*domain.Session) []*model.OcpiSession); ok {
		r0 = rf(ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiSession)
		}
	}

	return r0
}

// TokenToCdrTokenDomain provides a mock function with given fields: tkn
func (_m *SessionConverter) TokenToCdrTokenDomain(tkn *domain.Token) *domain.CdrToken {
	ret := _m.Called(tkn)

	var r0 *domain.CdrToken
	if rf, ok := ret.Get(0).(func(*domain.Token) *domain.CdrToken); ok {
		r0 = rf(tkn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CdrToken)
		}
	}

	return r0
}

// NewSessionConverter creates a new instance of SessionConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionConverter {
	mock := &SessionConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
