// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	backend "github.com/mikhailbolshakov/ocpi/backend"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mikhailbolshakov/ocpi/model"
)

// TariffConverter is an autogenerated mock type for the TariffConverter type
type TariffConverter struct {
	mock.Mock
}

// TariffBackendToDomain provides a mock function with given fields: trf
func (_m *TariffConverter) TariffBackendToDomain(trf *backend.Tariff) *domain.Tariff {
	ret := _m.Called(trf)

	var r0 *domain.Tariff
	if rf, ok := ret.Get(0).(func(*backend.Tariff) *domain.Tariff); ok {
		r0 = rf(trf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tariff)
		}
	}

	return r0
}

// TariffDomainToBackend provides a mock function with given fields: trf
func (_m *TariffConverter) TariffDomainToBackend(trf *domain.Tariff) *backend.Tariff {
	ret := _m.Called(trf)

	var r0 *backend.Tariff
	if rf, ok := ret.Get(0).(func(*domain.Tariff) *backend.Tariff); ok {
		r0 = rf(trf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Tariff)
		}
	}

	return r0
}

// TariffDomainToModel provides a mock function with given fields: trf
func (_m *TariffConverter) TariffDomainToModel(trf *domain.Tariff) *model.OcpiTariff {
	ret := _m.Called(trf)

	var r0 *model.OcpiTariff
	if rf, ok := ret.Get(0).(func(*domain.Tariff) *model.OcpiTariff); ok {
		r0 = rf(trf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiTariff)
		}
	}

	return r0
}

// TariffModelToDomain provides a mock function with given fields: trf, platformId
func (_m *TariffConverter) TariffModelToDomain(trf *model.OcpiTariff, platformId string) *domain.Tariff {
	ret := _m.Called(trf, platformId)

	var r0 *domain.Tariff
	if rf, ok := ret.Get(0).(func(*model.OcpiTariff, string) *domain.Tariff); ok {
		r0 = rf(trf, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tariff)
		}
	}

	return r0
}

// TariffsBackendToDomain provides a mock function with given fields: ts
func (_m *TariffConverter) TariffsBackendToDomain(ts []*backend.Tariff) []*domain.Tariff {
	ret := _m.Called(ts)

	var r0 []*domain.Tariff
	if rf, ok := ret.Get(0).(func([]*backend.Tariff) []*domain.Tariff); ok {
		r0 = rf(ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Tariff)
		}
	}

	return r0
}

// TariffsDomainToBackend provides a mock function with given fields: ts
func (_m *TariffConverter) TariffsDomainToBackend(ts []*domain.Tariff) []*backend.Tariff {
	ret := _m.Called(ts)

	var r0 []*backend.Tariff
	if rf, ok := ret.Get(0).(func([]*domain.Tariff) []*backend.Tariff); ok {
		r0 = rf(ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Tariff)
		}
	}

	return r0
}

// TariffsDomainToModel provides a mock function with given fields: ts
func (_m *TariffConverter) TariffsDomainToModel(ts []*domain.Tariff) []*model.OcpiTariff {
	ret := _m.Called(ts)

	var r0 []*model.OcpiTariff
	if rf, ok := ret.Get(0).(func([]*domain.Tariff) []*model.OcpiTariff); ok {
		r0 = rf(ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiTariff)
		}
	}

	return r0
}

// TariffsModelToDomain provides a mock function with given fields: ts, platformId
func (_m *TariffConverter) TariffsModelToDomain(ts []*model.OcpiTariff, platformId string) []*domain.Tariff {
	ret := _m.Called(ts, platformId)

	var r0 []*domain.Tariff
	if rf, ok := ret.Get(0).(func([]*model.OcpiTariff, string) []*domain.Tariff); ok {
		r0 = rf(ts, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Tariff)
		}
	}

	return r0
}

// NewTariffConverter creates a new instance of TariffConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTariffConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TariffConverter {
	mock := &TariffConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
