// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// TariffService is an autogenerated mock type for the TariffService type
type TariffService struct {
	mock.Mock
}

// DeleteTariffsByExtId provides a mock function with given fields: ctx, extId
func (_m *TariffService) DeleteTariffsByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTariff provides a mock function with given fields: ctx, trfId
func (_m *TariffService) GetTariff(ctx context.Context, trfId string) (*domain.Tariff, error) {
	ret := _m.Called(ctx, trfId)

	var r0 *domain.Tariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Tariff, error)); ok {
		return rf(ctx, trfId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Tariff); ok {
		r0 = rf(ctx, trfId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trfId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergeTariff provides a mock function with given fields: ctx, trf
func (_m *TariffService) MergeTariff(ctx context.Context, trf *domain.Tariff) (*domain.Tariff, error) {
	ret := _m.Called(ctx, trf)

	var r0 *domain.Tariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tariff) (*domain.Tariff, error)); ok {
		return rf(ctx, trf)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tariff) *domain.Tariff); ok {
		r0 = rf(ctx, trf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Tariff) error); ok {
		r1 = rf(ctx, trf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutTariff provides a mock function with given fields: ctx, trf
func (_m *TariffService) PutTariff(ctx context.Context, trf *domain.Tariff) (*domain.Tariff, error) {
	ret := _m.Called(ctx, trf)

	var r0 *domain.Tariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tariff) (*domain.Tariff, error)); ok {
		return rf(ctx, trf)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tariff) *domain.Tariff); ok {
		r0 = rf(ctx, trf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Tariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Tariff) error); ok {
		r1 = rf(ctx, trf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchTariffs provides a mock function with given fields: ctx, cr
func (_m *TariffService) SearchTariffs(ctx context.Context, cr *domain.TariffSearchCriteria) (*domain.TariffSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.TariffSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TariffSearchCriteria) (*domain.TariffSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TariffSearchCriteria) *domain.TariffSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TariffSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TariffSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Validate provides a mock function with given fields: ctx, trf
func (_m *TariffService) Validate(ctx context.Context, trf *domain.Tariff) error {
	ret := _m.Called(ctx, trf)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tariff) error); ok {
		r0 = rf(ctx, trf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTariffService creates a new instance of TariffService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTariffService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TariffService {
	mock := &TariffService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
