// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	model "github.com/mikhailbolshakov/ocpi/model"

	time "time"
)

// TariffUc is an autogenerated mock type for the TariffUc type
type TariffUc struct {
	mock.Mock
}

// OnLocalTariffChanged provides a mock function with given fields: ctx, trf
func (_m *TariffUc) OnLocalTariffChanged(ctx context.Context, trf *domain.Tariff) error {
	ret := _m.Called(ctx, trf)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Tariff) error); ok {
		r0 = rf(ctx, trf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteTariffPatch provides a mock function with given fields: ctx, platformId, trf
func (_m *TariffUc) OnRemoteTariffPatch(ctx context.Context, platformId string, trf *model.OcpiTariff) error {
	ret := _m.Called(ctx, platformId, trf)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiTariff) error); ok {
		r0 = rf(ctx, platformId, trf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteTariffPut provides a mock function with given fields: ctx, platformId, trf
func (_m *TariffUc) OnRemoteTariffPut(ctx context.Context, platformId string, trf *model.OcpiTariff) error {
	ret := _m.Called(ctx, platformId, trf)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiTariff) error); ok {
		r0 = rf(ctx, platformId, trf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteTariffsPull provides a mock function with given fields: ctx, from, to
func (_m *TariffUc) OnRemoteTariffsPull(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteTariffsPullWhenPushNotSupported provides a mock function with given fields: ctx, from, to
func (_m *TariffUc) OnRemoteTariffsPullWhenPushNotSupported(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTariffUc creates a new instance of TariffUc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTariffUc(t interface {
	mock.TestingT
	Cleanup(func())
}) *TariffUc {
	mock := &TariffUc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
