// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	backend "github.com/mikhailbolshakov/ocpi/backend"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	mock "github.com/stretchr/testify/mock"

	model "github.com/mikhailbolshakov/ocpi/model"
)

// TokenConverter is an autogenerated mock type for the TokenConverter type
type TokenConverter struct {
	mock.Mock
}

// TokenBackendToDomain provides a mock function with given fields: tkn, platformId
func (_m *TokenConverter) TokenBackendToDomain(tkn *backend.Token, platformId string) *domain.Token {
	ret := _m.Called(tkn, platformId)

	var r0 *domain.Token
	if rf, ok := ret.Get(0).(func(*backend.Token, string) *domain.Token); ok {
		r0 = rf(tkn, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	return r0
}

// TokenDomainToBackend provides a mock function with given fields: tkn
func (_m *TokenConverter) TokenDomainToBackend(tkn *domain.Token) *backend.Token {
	ret := _m.Called(tkn)

	var r0 *backend.Token
	if rf, ok := ret.Get(0).(func(*domain.Token) *backend.Token); ok {
		r0 = rf(tkn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Token)
		}
	}

	return r0
}

// TokenDomainToModel provides a mock function with given fields: tkn
func (_m *TokenConverter) TokenDomainToModel(tkn *domain.Token) *model.OcpiToken {
	ret := _m.Called(tkn)

	var r0 *model.OcpiToken
	if rf, ok := ret.Get(0).(func(*domain.Token) *model.OcpiToken); ok {
		r0 = rf(tkn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OcpiToken)
		}
	}

	return r0
}

// TokenModelToDomain provides a mock function with given fields: tkn, platformId
func (_m *TokenConverter) TokenModelToDomain(tkn *model.OcpiToken, platformId string) *domain.Token {
	ret := _m.Called(tkn, platformId)

	var r0 *domain.Token
	if rf, ok := ret.Get(0).(func(*model.OcpiToken, string) *domain.Token); ok {
		r0 = rf(tkn, platformId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	return r0
}

// TokensDomainToBackend provides a mock function with given fields: ts
func (_m *TokenConverter) TokensDomainToBackend(ts []*domain.Token) []*backend.Token {
	ret := _m.Called(ts)

	var r0 []*backend.Token
	if rf, ok := ret.Get(0).(func([]*domain.Token) []*backend.Token); ok {
		r0 = rf(ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Token)
		}
	}

	return r0
}

// TokensDomainToModel provides a mock function with given fields: ts
func (_m *TokenConverter) TokensDomainToModel(ts []*domain.Token) []*model.OcpiToken {
	ret := _m.Called(ts)

	var r0 []*model.OcpiToken
	if rf, ok := ret.Get(0).(func([]*domain.Token) []*model.OcpiToken); ok {
		r0 = rf(ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OcpiToken)
		}
	}

	return r0
}

// NewTokenConverter creates a new instance of TokenConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenConverter {
	mock := &TokenConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
