// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

// Base64Encode provides a mock function with given fields: tkn
func (_m *TokenGenerator) Base64Encode(tkn domain.PlatformToken) domain.PlatformToken {
	ret := _m.Called(tkn)

	var r0 domain.PlatformToken
	if rf, ok := ret.Get(0).(func(domain.PlatformToken) domain.PlatformToken); ok {
		r0 = rf(tkn)
	} else {
		r0 = ret.Get(0).(domain.PlatformToken)
	}

	return r0
}

// Generate provides a mock function with given fields: ctx
func (_m *TokenGenerator) Generate(ctx context.Context) (domain.PlatformToken, error) {
	ret := _m.Called(ctx)

	var r0 domain.PlatformToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (domain.PlatformToken, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) domain.PlatformToken); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.PlatformToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TryBase64Decode provides a mock function with given fields: token
func (_m *TokenGenerator) TryBase64Decode(token domain.PlatformToken) (domain.PlatformToken, bool) {
	ret := _m.Called(token)

	var r0 domain.PlatformToken
	var r1 bool
	if rf, ok := ret.Get(0).(func(domain.PlatformToken) (domain.PlatformToken, bool)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(domain.PlatformToken) domain.PlatformToken); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(domain.PlatformToken)
	}

	if rf, ok := ret.Get(1).(func(domain.PlatformToken) bool); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// NewTokenGenerator creates a new instance of TokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGenerator {
	mock := &TokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
