// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"
)

// TokenStorage is an autogenerated mock type for the TokenStorage type
type TokenStorage struct {
	mock.Mock
}

// DeleteTokensByExtId provides a mock function with given fields: ctx, extId
func (_m *TokenStorage) DeleteTokensByExtId(ctx context.Context, extId domain.PartyExtId) error {
	ret := _m.Called(ctx, extId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PartyExtId) error); ok {
		r0 = rf(ctx, extId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetToken provides a mock function with given fields: ctx, tknId
func (_m *TokenStorage) GetToken(ctx context.Context, tknId string) (*domain.Token, error) {
	ret := _m.Called(ctx, tknId)

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Token, error)); ok {
		return rf(ctx, tknId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Token); ok {
		r0 = rf(ctx, tknId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tknId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergeToken provides a mock function with given fields: ctx, tkn
func (_m *TokenStorage) MergeToken(ctx context.Context, tkn *domain.Token) error {
	ret := _m.Called(ctx, tkn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = rf(ctx, tkn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchTokens provides a mock function with given fields: ctx, cr
func (_m *TokenStorage) SearchTokens(ctx context.Context, cr *domain.TokenSearchCriteria) (*domain.TokenSearchResponse, error) {
	ret := _m.Called(ctx, cr)

	var r0 *domain.TokenSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TokenSearchCriteria) (*domain.TokenSearchResponse, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TokenSearchCriteria) *domain.TokenSearchResponse); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TokenSearchCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateToken provides a mock function with given fields: ctx, tkn
func (_m *TokenStorage) UpdateToken(ctx context.Context, tkn *domain.Token) error {
	ret := _m.Called(ctx, tkn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = rf(ctx, tkn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTokenStorage creates a new instance of TokenStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenStorage {
	mock := &TokenStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
