// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/mikhailbolshakov/ocpi/domain"

	model "github.com/mikhailbolshakov/ocpi/model"

	time "time"
)

// TokenUc is an autogenerated mock type for the TokenUc type
type TokenUc struct {
	mock.Mock
}

// GetOrCreateLocalToken provides a mock function with given fields: ctx, tkn
func (_m *TokenUc) GetOrCreateLocalToken(ctx context.Context, tkn *domain.Token) (*domain.Token, error) {
	ret := _m.Called(ctx, tkn)

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) (*domain.Token, error)); ok {
		return rf(ctx, tkn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) *domain.Token); ok {
		r0 = rf(ctx, tkn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Token) error); ok {
		r1 = rf(ctx, tkn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnLocalTokenChanged provides a mock function with given fields: ctx, tkn
func (_m *TokenUc) OnLocalTokenChanged(ctx context.Context, tkn *domain.Token) error {
	ret := _m.Called(ctx, tkn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = rf(ctx, tkn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteTokenPatch provides a mock function with given fields: ctx, platformId, tkn
func (_m *TokenUc) OnRemoteTokenPatch(ctx context.Context, platformId string, tkn *model.OcpiToken) error {
	ret := _m.Called(ctx, platformId, tkn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiToken) error); ok {
		r0 = rf(ctx, platformId, tkn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteTokenPut provides a mock function with given fields: ctx, platformId, tkn
func (_m *TokenUc) OnRemoteTokenPut(ctx context.Context, platformId string, tkn *model.OcpiToken) error {
	ret := _m.Called(ctx, platformId, tkn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.OcpiToken) error); ok {
		r0 = rf(ctx, platformId, tkn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteTokensPull provides a mock function with given fields: ctx, from, to
func (_m *TokenUc) OnRemoteTokensPull(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnRemoteTokensPullWhenPushNotSupported provides a mock function with given fields: ctx, from, to
func (_m *TokenUc) OnRemoteTokensPullWhenPushNotSupported(ctx context.Context, from *time.Time, to *time.Time) error {
	ret := _m.Called(ctx, from, to)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTokenUc creates a new instance of TokenUc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenUc(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenUc {
	mock := &TokenUc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
