// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeRemotePullServiceServer is an autogenerated mock type for the UnsafeRemotePullServiceServer type
type UnsafeRemotePullServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedRemotePullServiceServer provides a mock function with given fields:
func (_m *UnsafeRemotePullServiceServer) mustEmbedUnimplementedRemotePullServiceServer() {
	_m.Called()
}

// NewUnsafeRemotePullServiceServer creates a new instance of UnsafeRemotePullServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeRemotePullServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeRemotePullServiceServer {
	mock := &UnsafeRemotePullServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
