// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	ocpi "github.com/mikhailbolshakov/ocpi"
)

// webhookRestClient is an autogenerated mock type for the webhookRestClient type
type webhookRestClient struct {
	mock.Mock
}

// CallAsync provides a mock function with given fields: ctx, url, apiKey, event, payload
func (_m *webhookRestClient) CallAsync(ctx context.Context, url string, apiKey string, event string, payload interface{}) {
	_m.Called(ctx, url, apiKey, event, payload)
}

// Close provides a mock function with given fields: ctx
func (_m *webhookRestClient) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Init provides a mock function with given fields: ctx, config
func (_m *webhookRestClient) Init(ctx context.Context, config *ocpi.CfgWebHook) error {
	ret := _m.Called(ctx, config)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ocpi.CfgWebHook) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newWebhookRestClient creates a new instance of webhookRestClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newWebhookRestClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *webhookRestClient {
	mock := &webhookRestClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
