// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	backend "github.com/mikhailbolshakov/ocpi/backend"

	mock "github.com/stretchr/testify/mock"
)

// WebhookService is an autogenerated mock type for the WebhookService type
type WebhookService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, wh
func (_m *WebhookService) Create(ctx context.Context, wh *backend.Webhook) (*backend.Webhook, error) {
	ret := _m.Called(ctx, wh)

	var r0 *backend.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) (*backend.Webhook, error)); ok {
		return rf(ctx, wh)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) *backend.Webhook); ok {
		r0 = rf(ctx, wh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.Webhook) error); ok {
		r1 = rf(ctx, wh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUpdate provides a mock function with given fields: ctx, wh
func (_m *WebhookService) CreateUpdate(ctx context.Context, wh *backend.Webhook) (*backend.Webhook, error) {
	ret := _m.Called(ctx, wh)

	var r0 *backend.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) (*backend.Webhook, error)); ok {
		return rf(ctx, wh)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) *backend.Webhook); ok {
		r0 = rf(ctx, wh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.Webhook) error); ok {
		r1 = rf(ctx, wh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, whId
func (_m *WebhookService) Delete(ctx context.Context, whId string) error {
	ret := _m.Called(ctx, whId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, whId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, whId
func (_m *WebhookService) Get(ctx context.Context, whId string) (*backend.Webhook, error) {
	ret := _m.Called(ctx, whId)

	var r0 *backend.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*backend.Webhook, error)); ok {
		return rf(ctx, whId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *backend.Webhook); ok {
		r0 = rf(ctx, whId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, whId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, cr
func (_m *WebhookService) Search(ctx context.Context, cr *backend.SearchWebhookCriteria) ([]*backend.Webhook, error) {
	ret := _m.Called(ctx, cr)

	var r0 []*backend.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.SearchWebhookCriteria) ([]*backend.Webhook, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.SearchWebhookCriteria) []*backend.Webhook); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.SearchWebhookCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, wh
func (_m *WebhookService) Update(ctx context.Context, wh *backend.Webhook) (*backend.Webhook, error) {
	ret := _m.Called(ctx, wh)

	var r0 *backend.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) (*backend.Webhook, error)); ok {
		return rf(ctx, wh)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) *backend.Webhook); ok {
		r0 = rf(ctx, wh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.Webhook) error); ok {
		r1 = rf(ctx, wh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWebhookService creates a new instance of WebhookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhookService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhookService {
	mock := &WebhookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
