// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	backend "github.com/mikhailbolshakov/ocpi/backend"

	mock "github.com/stretchr/testify/mock"
)

// WebhookStorage is an autogenerated mock type for the WebhookStorage type
type WebhookStorage struct {
	mock.Mock
}

// CreateWebhook provides a mock function with given fields: ctx, wh
func (_m *WebhookStorage) CreateWebhook(ctx context.Context, wh *backend.Webhook) error {
	ret := _m.Called(ctx, wh)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) error); ok {
		r0 = rf(ctx, wh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWebhook provides a mock function with given fields: ctx, whId
func (_m *WebhookStorage) DeleteWebhook(ctx context.Context, whId string) error {
	ret := _m.Called(ctx, whId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, whId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWebhook provides a mock function with given fields: ctx, whId
func (_m *WebhookStorage) GetWebhook(ctx context.Context, whId string) (*backend.Webhook, error) {
	ret := _m.Called(ctx, whId)

	var r0 *backend.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*backend.Webhook, error)); ok {
		return rf(ctx, whId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *backend.Webhook); ok {
		r0 = rf(ctx, whId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backend.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, whId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergeWebhook provides a mock function with given fields: ctx, wh
func (_m *WebhookStorage) MergeWebhook(ctx context.Context, wh *backend.Webhook) error {
	ret := _m.Called(ctx, wh)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) error); ok {
		r0 = rf(ctx, wh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchWebhook provides a mock function with given fields: ctx, cr
func (_m *WebhookStorage) SearchWebhook(ctx context.Context, cr *backend.SearchWebhookCriteria) ([]*backend.Webhook, error) {
	ret := _m.Called(ctx, cr)

	var r0 []*backend.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.SearchWebhookCriteria) ([]*backend.Webhook, error)); ok {
		return rf(ctx, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.SearchWebhookCriteria) []*backend.Webhook); ok {
		r0 = rf(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backend.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.SearchWebhookCriteria) error); ok {
		r1 = rf(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWebhook provides a mock function with given fields: ctx, wh
func (_m *WebhookStorage) UpdateWebhook(ctx context.Context, wh *backend.Webhook) error {
	ret := _m.Called(ctx, wh)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.Webhook) error); ok {
		r0 = rf(ctx, wh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWebhookStorage creates a new instance of WebhookStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhookStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhookStorage {
	mock := &WebhookStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
