// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WebhookRepository is an autogenerated mock type for the WebhookRepository type
type WebhookRepository struct {
	mock.Mock
}

// CallAsync provides a mock function with given fields: ctx, url, apiKey, event, payload
func (_m *WebhookRepository) CallAsync(ctx context.Context, url string, apiKey string, event string, payload interface{}) {
	_m.Called(ctx, url, apiKey, event, payload)
}

// NewWebhookRepository creates a new instance of WebhookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhookRepository {
	mock := &WebhookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
