// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: proto/ocpi.proto

package ocpi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RemotePullService_PullParties_FullMethodName                           = "/ocpi.RemotePullService/PullParties"
	RemotePullService_PullHubClientInfo_FullMethodName                     = "/ocpi.RemotePullService/PullHubClientInfo"
	RemotePullService_PullHubClientInfoWhenPushNotSupported_FullMethodName = "/ocpi.RemotePullService/PullHubClientInfoWhenPushNotSupported"
	RemotePullService_PullLocations_FullMethodName                         = "/ocpi.RemotePullService/PullLocations"
	RemotePullService_PullLocationsWhenPushNotSupported_FullMethodName     = "/ocpi.RemotePullService/PullLocationsWhenPushNotSupported"
	RemotePullService_PullTariffs_FullMethodName                           = "/ocpi.RemotePullService/PullTariffs"
	RemotePullService_PullTariffsWhenPushNotSupported_FullMethodName       = "/ocpi.RemotePullService/PullTariffsWhenPushNotSupported"
	RemotePullService_PullTokens_FullMethodName                            = "/ocpi.RemotePullService/PullTokens"
	RemotePullService_PullTokensWhenPushNotSupported_FullMethodName        = "/ocpi.RemotePullService/PullTokensWhenPushNotSupported"
	RemotePullService_PullSessions_FullMethodName                          = "/ocpi.RemotePullService/PullSessions"
	RemotePullService_PullSessionsWhenPushNotSupported_FullMethodName      = "/ocpi.RemotePullService/PullSessionsWhenPushNotSupported"
	RemotePullService_PullCdrs_FullMethodName                              = "/ocpi.RemotePullService/PullCdrs"
	RemotePullService_PullCdrsWhenPushNotSupported_FullMethodName          = "/ocpi.RemotePullService/PullCdrsWhenPushNotSupported"
)

// RemotePullServiceClient is the client API for RemotePullService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemotePullServiceClient interface {
	// PullParties retrieves parties data from remote platforms
	PullParties(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullHubClientInfo retrieves client info data from remote platforms
	PullHubClientInfo(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullHubClientInfo retrieves client info data from remote platforms when platforms don't support push
	PullHubClientInfoWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullLocations retrieves locations data from remote platforms
	PullLocations(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullLocations retrieves locations data from remote platforms when platforms don't support push
	PullLocationsWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullTariffs retrieves tariffs data from remote platforms
	PullTariffs(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullTariffs retrieves tariffs data from remote platforms when platforms don't support push
	PullTariffsWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullTokens retrieves tokens data from remote platforms
	PullTokens(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullTokens retrieves tokens data from remote platforms when platforms don't support push
	PullTokensWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullSessions retrieves sessions data from remote platforms
	PullSessions(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullSessions retrieves sessions data from remote platforms when platforms don't support push
	PullSessionsWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullSessions retrieves sessions data from remote platforms
	PullCdrs(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// PullSessions retrieves sessions data from remote platforms when platforms don't support push
	PullCdrsWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type remotePullServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemotePullServiceClient(cc grpc.ClientConnInterface) RemotePullServiceClient {
	return &remotePullServiceClient{cc}
}

func (c *remotePullServiceClient) PullParties(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullParties_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullHubClientInfo(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullHubClientInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullHubClientInfoWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullHubClientInfoWhenPushNotSupported_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullLocations(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullLocations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullLocationsWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullLocationsWhenPushNotSupported_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullTariffs(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullTariffs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullTariffsWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullTariffsWhenPushNotSupported_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullTokens(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullTokens_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullTokensWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullTokensWhenPushNotSupported_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullSessions(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullSessions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullSessionsWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullSessionsWhenPushNotSupported_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullCdrs(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullCdrs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remotePullServiceClient) PullCdrsWhenPushNotSupported(ctx context.Context, in *RemotePullRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, RemotePullService_PullCdrsWhenPushNotSupported_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemotePullServiceServer is the server API for RemotePullService service.
// All implementations must embed UnimplementedRemotePullServiceServer
// for forward compatibility
type RemotePullServiceServer interface {
	// PullParties retrieves parties data from remote platforms
	PullParties(context.Context, *EmptyRequest) (*EmptyResponse, error)
	// PullHubClientInfo retrieves client info data from remote platforms
	PullHubClientInfo(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullHubClientInfo retrieves client info data from remote platforms when platforms don't support push
	PullHubClientInfoWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullLocations retrieves locations data from remote platforms
	PullLocations(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullLocations retrieves locations data from remote platforms when platforms don't support push
	PullLocationsWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullTariffs retrieves tariffs data from remote platforms
	PullTariffs(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullTariffs retrieves tariffs data from remote platforms when platforms don't support push
	PullTariffsWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullTokens retrieves tokens data from remote platforms
	PullTokens(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullTokens retrieves tokens data from remote platforms when platforms don't support push
	PullTokensWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullSessions retrieves sessions data from remote platforms
	PullSessions(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullSessions retrieves sessions data from remote platforms when platforms don't support push
	PullSessionsWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullSessions retrieves sessions data from remote platforms
	PullCdrs(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	// PullSessions retrieves sessions data from remote platforms when platforms don't support push
	PullCdrsWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedRemotePullServiceServer()
}

// UnimplementedRemotePullServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRemotePullServiceServer struct {
}

func (UnimplementedRemotePullServiceServer) PullParties(context.Context, *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullParties not implemented")
}
func (UnimplementedRemotePullServiceServer) PullHubClientInfo(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullHubClientInfo not implemented")
}
func (UnimplementedRemotePullServiceServer) PullHubClientInfoWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullHubClientInfoWhenPushNotSupported not implemented")
}
func (UnimplementedRemotePullServiceServer) PullLocations(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullLocations not implemented")
}
func (UnimplementedRemotePullServiceServer) PullLocationsWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullLocationsWhenPushNotSupported not implemented")
}
func (UnimplementedRemotePullServiceServer) PullTariffs(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullTariffs not implemented")
}
func (UnimplementedRemotePullServiceServer) PullTariffsWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullTariffsWhenPushNotSupported not implemented")
}
func (UnimplementedRemotePullServiceServer) PullTokens(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullTokens not implemented")
}
func (UnimplementedRemotePullServiceServer) PullTokensWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullTokensWhenPushNotSupported not implemented")
}
func (UnimplementedRemotePullServiceServer) PullSessions(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullSessions not implemented")
}
func (UnimplementedRemotePullServiceServer) PullSessionsWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullSessionsWhenPushNotSupported not implemented")
}
func (UnimplementedRemotePullServiceServer) PullCdrs(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullCdrs not implemented")
}
func (UnimplementedRemotePullServiceServer) PullCdrsWhenPushNotSupported(context.Context, *RemotePullRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullCdrsWhenPushNotSupported not implemented")
}
func (UnimplementedRemotePullServiceServer) mustEmbedUnimplementedRemotePullServiceServer() {}

// UnsafeRemotePullServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemotePullServiceServer will
// result in compilation errors.
type UnsafeRemotePullServiceServer interface {
	mustEmbedUnimplementedRemotePullServiceServer()
}

func RegisterRemotePullServiceServer(s grpc.ServiceRegistrar, srv RemotePullServiceServer) {
	s.RegisterService(&RemotePullService_ServiceDesc, srv)
}

func _RemotePullService_PullParties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullParties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullParties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullParties(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullHubClientInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullHubClientInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullHubClientInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullHubClientInfo(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullHubClientInfoWhenPushNotSupported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullHubClientInfoWhenPushNotSupported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullHubClientInfoWhenPushNotSupported_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullHubClientInfoWhenPushNotSupported(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullLocations(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullLocationsWhenPushNotSupported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullLocationsWhenPushNotSupported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullLocationsWhenPushNotSupported_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullLocationsWhenPushNotSupported(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullTariffs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullTariffs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullTariffs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullTariffs(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullTariffsWhenPushNotSupported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullTariffsWhenPushNotSupported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullTariffsWhenPushNotSupported_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullTariffsWhenPushNotSupported(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullTokens(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullTokensWhenPushNotSupported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullTokensWhenPushNotSupported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullTokensWhenPushNotSupported_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullTokensWhenPushNotSupported(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullSessions(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullSessionsWhenPushNotSupported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullSessionsWhenPushNotSupported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullSessionsWhenPushNotSupported_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullSessionsWhenPushNotSupported(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullCdrs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullCdrs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullCdrs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullCdrs(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemotePullService_PullCdrsWhenPushNotSupported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemotePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemotePullServiceServer).PullCdrsWhenPushNotSupported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemotePullService_PullCdrsWhenPushNotSupported_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemotePullServiceServer).PullCdrsWhenPushNotSupported(ctx, req.(*RemotePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemotePullService_ServiceDesc is the grpc.ServiceDesc for RemotePullService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemotePullService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocpi.RemotePullService",
	HandlerType: (*RemotePullServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullParties",
			Handler:    _RemotePullService_PullParties_Handler,
		},
		{
			MethodName: "PullHubClientInfo",
			Handler:    _RemotePullService_PullHubClientInfo_Handler,
		},
		{
			MethodName: "PullHubClientInfoWhenPushNotSupported",
			Handler:    _RemotePullService_PullHubClientInfoWhenPushNotSupported_Handler,
		},
		{
			MethodName: "PullLocations",
			Handler:    _RemotePullService_PullLocations_Handler,
		},
		{
			MethodName: "PullLocationsWhenPushNotSupported",
			Handler:    _RemotePullService_PullLocationsWhenPushNotSupported_Handler,
		},
		{
			MethodName: "PullTariffs",
			Handler:    _RemotePullService_PullTariffs_Handler,
		},
		{
			MethodName: "PullTariffsWhenPushNotSupported",
			Handler:    _RemotePullService_PullTariffsWhenPushNotSupported_Handler,
		},
		{
			MethodName: "PullTokens",
			Handler:    _RemotePullService_PullTokens_Handler,
		},
		{
			MethodName: "PullTokensWhenPushNotSupported",
			Handler:    _RemotePullService_PullTokensWhenPushNotSupported_Handler,
		},
		{
			MethodName: "PullSessions",
			Handler:    _RemotePullService_PullSessions_Handler,
		},
		{
			MethodName: "PullSessionsWhenPushNotSupported",
			Handler:    _RemotePullService_PullSessionsWhenPushNotSupported_Handler,
		},
		{
			MethodName: "PullCdrs",
			Handler:    _RemotePullService_PullCdrs_Handler,
		},
		{
			MethodName: "PullCdrsWhenPushNotSupported",
			Handler:    _RemotePullService_PullCdrsWhenPushNotSupported_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ocpi.proto",
}
